export const brandsByVehicleType = {
  // for "cars" and "sports cars"
  cars: [
    { label: 'A2B', value: 'a2b' },
    { label: 'Addmotor', value: 'addmotor' },
    { label: 'Alchemy', value: 'alchemy' },
    { label: 'All-City', value: 'allcity' },
    { label: 'Allied Cycle Works', value: 'alliedcycleworks' },
    { label: 'Ancheer', value: 'ancheer' },
    { label: 'Ariel Rider', value: 'arielrider' },
    { label: 'Aventon', value: 'aventon' },
    { label: 'Bacchetta', value: 'bacchetta' },
    { label: 'Bakcou', value: 'bakcou' },
    { label: 'Basso', value: 'basso' },
    { label: 'Batch', value: 'batch' },
    { label: 'Be One', value: 'beone' },
    { label: 'Benno', value: 'benno' },
    { label: 'BH', value: 'bh' },
    { label: 'BH Bikes', value: 'bhbikes' },
    { label: 'Bianchi', value: 'bianchi' },
    { label: 'Bintelli', value: 'bintelli' },
    { label: 'Birdy', value: 'birdy' },
    { label: 'Blix', value: 'blix' },
    { label: 'BMC', value: 'bmc' },
    { label: 'Boardman', value: 'boardman' },
    { label: 'Bombtrack', value: 'bombtrack' },
    { label: 'Breezer', value: 'breezer' },
    { label: 'Brompton', value: 'brompton' },
    { label: 'Bulls', value: 'bulls' },
    { label: 'Burley', value: 'burley' },
    { label: 'Cannondale', value: 'cannondale' },
    { label: 'Canyon', value: 'canyon' },
    { label: 'Cervélo', value: 'cervelo' },
    { label: 'Charge', value: 'charge' },
    { label: 'Cinelli', value: 'cinelli' },
    { label: 'Civia', value: 'civia' },
    { label: 'Colnago', value: 'colnago' },
    { label: 'Commencal', value: 'commencal' },
    { label: 'Co-op Cycles', value: 'coopcycles' },
    { label: 'Cotic', value: 'cotic' },
    { label: 'Cube', value: 'cube' },
    { label: 'Dahon', value: 'dahon' },
    { label: 'Dawes', value: 'dawes' },
    { label: 'De Rosa', value: 'derosa' },
    { label: 'Devinci', value: 'devinci' },
    { label: 'Diamondback', value: 'diamondback' },
    { label: 'DJ Bikes', value: 'djbikes' },
    { label: 'Ecotric', value: 'ecotric' },
    { label: 'Eddy Merckx', value: 'eddycycles' },
    { label: 'E-Joe', value: 'ejoe' },
    { label: 'Electra', value: 'electra' },
    { label: 'Elliptigo', value: 'elliptigo' },
    { label: 'Ellis', value: 'ellis' },
    { label: 'Ellsworth', value: 'ellsworth' },
    { label: 'Emojo', value: 'emojo' },
    { label: 'Engwe', value: 'engwe' },
    { label: 'Enzo', value: 'enzo' },
    { label: 'Eunorau', value: 'eunorau' },
    { label: 'Evelo', value: 'evelo' },
    { label: 'Evercross', value: 'evercross' },
    { label: 'Faraday', value: 'faraday' },
    { label: 'Felt', value: 'felt' },
    { label: 'Flyer', value: 'flyer' },
    { label: 'Focus', value: 'focus' },
    { label: 'Fondriest', value: 'fondriest' },
    { label: 'Fuji', value: 'fuji' },
    { label: 'Gazelle', value: 'gazelle' },
    { label: 'Generic', value: 'generic' },
    { label: 'Genesis', value: 'genesis' },
    { label: 'GenZe', value: 'genze' },
    { label: 'G-Force', value: 'gforce' },
    { label: 'Ghost', value: 'ghost' },
    { label: 'Giant', value: 'giant' },
    { label: 'Gocycle', value: 'gocycle' },
    { label: 'GreenBike', value: 'greenbike' },
    { label: 'Greenspeed', value: 'greenspeed' },
    { label: 'GT', value: 'gt' },
    { label: 'Haibike', value: 'haibike' },
    { label: 'Haro', value: 'haro' },
    { label: 'Hase', value: 'hase' },
    { label: 'Himiway', value: 'himiway' },
    { label: 'Holdsworth', value: 'holdsworth' },
    { label: 'HP Velotechnik', value: 'hpvelotechnik' },
    { label: 'Hyper', value: 'hyper' },
    { label: 'Ibis', value: 'ibis' },
    { label: 'ICE Trikes', value: 'icetrikes' },
    { label: 'iZip', value: 'izip' },
    { label: 'Jamis', value: 'jamis' },
    { label: 'Juiced Bikes', value: 'juicedbikes' },
    { label: 'Kalkhoff', value: 'kalkhoff' },
    { label: 'KBO', value: 'kbo' },
    { label: 'Kestrel', value: 'kestrel' },
    { label: 'Kettler', value: 'kettler' },
    { label: 'KHS', value: 'khs' },
    { label: 'Koga', value: 'koga' },
    { label: 'Kona', value: 'kona' },
    { label: 'Kross', value: 'kross' },
    { label: 'Lapierre', value: 'lapierre' },
    { label: 'Lectric', value: 'lectric' },
    { label: 'Litespeed', value: 'litespeed' },
    { label: 'Liteville', value: 'liteville' },
    { label: 'Look', value: 'look' },
    { label: 'Magnum', value: 'magnum' },
    { label: 'Marin', value: 'marin' },
    { label: 'Masi', value: 'masi' },
    { label: 'Merida', value: 'merida' },
    { label: 'Miyata', value: 'miyata' },
    { label: 'Mondraker', value: 'mondraker' },
    { label: 'Mongoose', value: 'mongoose' },
    { label: 'Montague', value: 'montague' },
    { label: 'Moots', value: 'moots' },
    { label: 'Motiv', value: 'motiv' },
    { label: 'Motobecane', value: 'motobecane' },
    { label: 'Moustache', value: 'moustache' },
    { label: 'Nakto', value: 'nakto' },
    { label: 'NCM', value: 'ncm' },
    { label: 'Niner', value: 'niner' },
    { label: 'Nishiki', value: 'nishiki' },
    { label: 'Noah’s Ark', value: 'noahsark' },
    { label: 'Norco', value: 'norco' },
    { label: 'NS Bikes', value: 'nsbikes' },
    { label: 'Orbea', value: 'orbea' },
    { label: 'Pedego', value: 'pedego' },
    { label: 'Pinarello', value: 'pinarello' },
    { label: 'Pinnacle', value: 'pinnacle' },
    { label: 'Pivot', value: 'pivot' },
    { label: 'Polygon', value: 'polygon' },
    { label: 'Priority', value: 'priority' },
    { label: 'ProdecoTech', value: 'prodecotech' },
    { label: 'Propella', value: 'propella' },
    { label: 'Pure Cycles', value: 'purecycles' },
    { label: 'QuietKat', value: 'quietkat' },
    { label: 'Rad', value: 'rad' },
    { label: 'Rad Power Bikes', value: 'radpowerbikes' },
    { label: 'Radon', value: 'radon' },
    { label: 'Raleigh', value: 'raleigh' },
    { label: 'Revel', value: 'revel' },
    { label: 'Ribble', value: 'ribble' },
    { label: 'Ride1Up', value: 'ride1up' },
    { label: 'Ridley', value: 'ridley' },
    { label: 'Riese & Müller', value: 'riesemuller' },
    { label: 'Ritchey', value: 'ritchey' },
    { label: 'Rockrider', value: 'rockrider' },
    { label: 'Rocky Mountain', value: 'rockymountain' },
    { label: 'Salsa', value: 'salsa' },
    { label: 'Santa Cruz', value: 'santacruz' },
    { label: 'Saracen', value: 'saracen' },
    { label: 'Schwinn', value: 'schwinn' },
    { label: 'Scott', value: 'scott' },
    { label: 'Sixthreezero', value: 'sixthreezero' },
    { label: 'Sonder', value: 'sonder' },
    { label: 'Sondors', value: 'sondors' },
    { label: 'Specialized', value: 'specialized' },
    { label: 'Stark Drive', value: 'starkdrive' },
    { label: 'State Bicycle Co.', value: 'statebicycleco' },
    { label: 'Stevens', value: 'stevens' },
    { label: 'Stromer', value: 'stromer' },
    { label: 'Surly', value: 'surly' },
    { label: 'Swagtron', value: 'swagtron' },
    { label: 'Tern', value: 'tern' },
    { label: 'Terratrike', value: 'terratrike' },
    { label: 'Time', value: 'time' },
    { label: 'Tommaso', value: 'tommaso' },
    { label: 'Trek', value: 'trek' },
    { label: 'Turner', value: 'turner' },
    { label: 'Univega', value: 'univega' },
    { label: 'Van Nicholas', value: 'vannicholas' },
    { label: 'VanMoof', value: 'vanmoof' },
    { label: 'Velotric', value: 'velotric' },
    { label: 'Vitória', value: 'vitoria' },
    { label: 'VoltBike', value: 'voltbike' },
    { label: 'Vvolt', value: 'vvolt' },
    { label: 'Watt', value: 'watt' },
    { label: 'Whyte', value: 'whyte' },
    { label: 'Wilier', value: 'wilier' },
    { label: 'Wilier Triestina', value: 'wiliertriestina' },
    { label: 'Wing', value: 'wing' },
    { label: 'Woom', value: 'woom' },
    { label: 'Xtracycle', value: 'xtracycle' },
    { label: 'Yamaha', value: 'yamaha' },
    { label: 'Yeti', value: 'yeti' },
    { label: 'Yeti Cycles', value: 'yeticycles' },
    { label: 'YT Industries', value: 'ytindustries' },
    { label: 'Yuba', value: 'yuba' },
    { label: 'Zerode', value: 'zerode' },
    { label: 'Zigo', value: 'zigo' },
    { label: 'Zizzo', value: 'zizzo' },
    { label: 'Zobop', value: 'zobop' },
  ],

  // cars end

  // for motorcycles and sports bikes
  bikes: [
    { label: 'AJP', value: 'ajp' },
    { label: 'Alta Motors', value: 'alta_motors' },
    { label: 'Ampere Vehicles', value: 'ampere_vehicles' },
    { label: 'Ariel Motorcycles', value: 'ariel_motorcycles' },
    { label: 'Arcimoto', value: 'arcimoto' },
    { label: 'Aprilia', value: 'aprilia' },
    { label: 'Atumobile', value: 'atumobile' },
    { label: 'Ather Energy', value: 'ather_energy' },
    { label: 'Bajaj Auto', value: 'bajaj_auto' },
    { label: 'Benelli', value: 'benelli' },
    { label: 'Beta Motor', value: 'beta_motor' },
    { label: 'Big Dog Motorcycles', value: 'big_dog_motorcycles' },
    { label: 'Bimota', value: 'bimota' },
    { label: 'Brammo', value: 'brammo' },
    { label: 'Brixton Motorcycles', value: 'brixton_motorcycles' },
    { label: 'Brough Superior', value: 'brough_superior' },
    {
      label: 'Brutus Electric Motorcycles',
      value: 'brutus_electric_motorcycles',
    },
    { label: 'Brutus Motorcycles', value: 'brutus_motorcycles' },
    { label: 'BSA Motorcycles', value: 'bsa_motorcycles' },
    { label: 'Cake', value: 'cake' },
    { label: 'Can-Am', value: 'can_am' },
    { label: 'CFMoto', value: 'cfmoto' },
    { label: 'Cleveland CycleWerks', value: 'cleveland_cyclewerks' },
    { label: 'Cobra Motorcycles', value: 'cobra_motorcycles' },
    { label: 'Confederate Motors', value: 'confederate_motors' },
    { label: 'Curtiss Motorcycles', value: 'curtiss_motorcycles' },
    { label: 'Damon Motors', value: 'damon_motors' },
    { label: 'Dahon', value: 'dahon' },
    { label: 'Derbi', value: 'derbi' },
    { label: 'Ducati', value: 'ducati' },
    { label: 'E-Moto Tech', value: 'e_moto_tech' },
    { label: 'EeVe India', value: 'eeve_india' },
    { label: 'Energica', value: 'energica' },
    { label: 'Emflux Motors', value: 'emflux_motors' },
    { label: 'Evoke Motorcycles', value: 'evoke_motorcycles' },
    { label: 'Excelsior-Henderson', value: 'excelsior_henderson' },
    { label: 'Fantic Motor', value: 'fantic_motor' },
    { label: 'Fuell', value: 'fuell' },
    { label: 'Gilera', value: 'gilera' },
    { label: 'Gogoro', value: 'gogoro' },
    { label: 'Greaves Cotton', value: 'greaves_cotton' },
    { label: 'Gravton Motors', value: 'gravton_motors' },
    { label: 'Haojue', value: 'haojue' },
    { label: 'Harley-Davidson', value: 'harley_davidson' },
    { label: 'Hero Electric', value: 'hero_electric' },
    { label: 'Hero MotoCorp', value: 'hero_motocorp' },
    { label: 'Hesketh Motorcycles', value: 'hesketh_motorcycles' },
    { label: 'Husaberg', value: 'husaberg' },
    { label: 'Husqvarna Motorcycles', value: 'husqvarna_motorcycles' },
    { label: 'Hyosung', value: 'hyosung' },
  ],
  // bikes end

  //for bicycles and electric cycles
  cycles: [
    { label: 'Generic', value: 'generic' },
    { label: 'Trek', value: 'trek' },
    { label: 'Specialized', value: 'specialized' },
    { label: 'Giant', value: 'giant' },
    { label: 'Cannondale', value: 'cannondale' },
    { label: 'Scott', value: 'scott' },
    { label: 'Santa Cruz', value: 'santa_cruz' },
    { label: 'Yeti', value: 'yeti' },
    { label: 'Merida', value: 'merida' },
    { label: 'Bianchi', value: 'bianchi' },
    { label: 'Cervélo', value: 'cervelo' },
    { label: 'Pinarello', value: 'pinarello' },
    { label: 'Colnago', value: 'colnago' },
    { label: 'Orbea', value: 'orbea' },
    { label: 'Raleigh', value: 'raleigh' },
    { label: 'Kona', value: 'kona' },
    { label: 'GT', value: 'gt' },
    { label: 'Marin', value: 'marin' },
    { label: 'Fuji', value: 'fuji' },
    { label: 'Focus', value: 'focus' },
    { label: 'Diamondback', value: 'diamondback' },
    { label: 'Canyon', value: 'canyon' },
    { label: 'Ghost', value: 'ghost' },
    { label: 'Norco', value: 'norco' },
    { label: 'Felt', value: 'felt' },
    { label: 'Polygon', value: 'polygon' },
    { label: 'Cube', value: 'cube' },
    { label: 'Haibike', value: 'haibike' },
    { label: 'Rad Power Bikes', value: 'rad_power_bikes' },
    { label: 'Bulls', value: 'bulls' },
    { label: 'Lapierre', value: 'lapierre' },
    { label: 'Niner', value: 'niner' },
    { label: 'Pivot', value: 'pivot' },
    { label: 'Mondraker', value: 'mondraker' },
    { label: 'Rocky Mountain', value: 'rocky_mountain' },
    { label: 'Yuba', value: 'yuba' },
    { label: 'Surly', value: 'surly' },
    { label: 'Tern', value: 'tern' },
    { label: 'Gazelle', value: 'gazelle' },
    { label: 'Charge', value: 'charge' },
    { label: 'Lectric', value: 'lectric' },
    { label: 'Ancheer', value: 'ancheer' },
    { label: 'Aventon', value: 'aventon' },
    { label: 'Juiced Bikes', value: 'juiced_bikes' },
    { label: 'VanMoof', value: 'vanmoof' },
    { label: 'Riese & Müller', value: 'riese_muller' },
    { label: 'Stromer', value: 'stromer' },
    { label: 'Pedego', value: 'pedego' },
    { label: 'Radon', value: 'radon' },
    { label: 'BH Bikes', value: 'bh_bikes' },
    { label: 'Look', value: 'look' },
    { label: 'Jamis', value: 'jamis' },
    { label: 'Ibis', value: 'ibis' },
    { label: 'Saracen', value: 'saracen' },
    { label: 'Ellsworth', value: 'ellsworth' },
    { label: 'Liteville', value: 'liteville' },
    { label: 'Salsa', value: 'salsa' },
    { label: 'Cotic', value: 'cotic' },
    { label: 'Ritchey', value: 'ritchey' },
    { label: 'Alchemy', value: 'alchemy' },
    { label: 'Whyte', value: 'whyte' },
    { label: 'Kross', value: 'kross' },
    { label: 'Stevens', value: 'stevens' },
    { label: 'Masi', value: 'masi' },
    { label: 'Wilier Triestina', value: 'wilier_triestina' },
    { label: 'Breezer', value: 'breezer' },
    { label: 'Devinci', value: 'devinci' },
    { label: 'Sonder', value: 'sonder' },
    { label: 'Co-op Cycles', value: 'co_op_cycles' },
    { label: 'KHS', value: 'khs' },
    { label: 'All-City', value: 'all_city' },
    { label: 'Bombtrack', value: 'bombtrack' },
    { label: 'Moots', value: 'moots' },
    { label: 'Ribble', value: 'ribble' },
    { label: 'Holdsworth', value: 'holdsworth' },
    { label: 'Genesis', value: 'genesis' },
    { label: 'Dawes', value: 'dawes' },
    { label: 'Charge', value: 'charge' },
    { label: 'Boardman', value: 'boardman' },
    { label: 'Haro', value: 'haro' },
    { label: 'NS Bikes', value: 'ns_bikes' },
    { label: 'Commencal', value: 'commencal' },
    { label: 'BMC', value: 'bmc' },
    { label: 'Ghost', value: 'ghost' },
    { label: 'Univega', value: 'univega' },
    { label: 'Ridley', value: 'ridley' },
    { label: 'Schwinn', value: 'schwinn' },
    { label: 'Kestrel', value: 'kestrel' },
    { label: 'Motobecane', value: 'motobecane' },
    { label: 'Cinelli', value: 'cinelli' },
    { label: 'Time', value: 'time' },
    { label: 'Focus', value: 'focus' },
    { label: 'Woom', value: 'woom' },
    { label: 'Electra', value: 'electra' },
    { label: 'Priority', value: 'priority' },
    { label: 'Tommaso', value: 'tommaso' },
    { label: 'State Bicycle Co.', value: 'state_bicycle_co' },
    { label: 'Allied Cycle Works', value: 'allied_cycle_works' },
    { label: 'Van Nicholas', value: 'van_nicholas' },
    { label: 'Be One', value: 'be_one' },
    { label: 'Bianchi', value: 'bianchi' },
    { label: 'Raleigh', value: 'raleigh' },
    { label: 'Nishiki', value: 'nishiki' },
    { label: 'Motiv', value: 'motiv' },
    { label: 'Diamondback', value: 'diamondback' },
    { label: 'Fuji', value: 'fuji' },
    { label: 'GT', value: 'gt' },
    { label: 'Jamis', value: 'jamis' },
    { label: 'Marin', value: 'marin' },
    { label: 'Mongoose', value: 'mongoose' },
    { label: 'Colnago', value: 'colnago' },
    { label: 'De Rosa', value: 'de_rosa' },
    { label: 'Pinarello', value: 'pinarello' },
    { label: 'Basso', value: 'basso' },
    { label: 'Wilier', value: 'wilier' },
    { label: 'Fondriest', value: 'fondriest' },
    { label: 'Look', value: 'look' },
    { label: 'Salsa', value: 'salsa' },
    { label: 'Surly', value: 'surly' },
    { label: 'Ellis', value: 'ellis' },
    { label: 'Eddy Merckx', value: 'eddy_merckx' },
    { label: 'BMC', value: 'bmc' },
    { label: 'Koga', value: 'koga' },
    { label: 'Miyata', value: 'miyata' },
    { label: 'Orbea', value: 'orbea' },
    { label: 'Lapierre', value: 'lapierre' },
    { label: 'BH', value: 'bh' },
    { label: 'Look', value: 'look' },
    { label: 'Time', value: 'time' },
    { label: 'Vitória', value: 'vitoria' },
    { label: 'Vanmoof', value: 'vanmoof' },
    { label: 'Brompton', value: 'brompton' },
    { label: 'Birdy', value: 'birdy' },
    { label: 'Dahon', value: 'dahon' },
    { label: 'Tern', value: 'tern' },
    { label: 'Riese & Müller', value: 'riese_muller' },
    { label: 'Hase', value: 'hase' },
    { label: 'ICE Trikes', value: 'ice_trikes' },
    { label: 'Bacchetta', value: 'bacchetta' },
    { label: 'Greenspeed', value: 'greenspeed' },
    { label: 'Terratrike', value: 'terratrike' },
    { label: 'HP Velotechnik', value: 'hp_velotechnik' },
    { label: 'A2B', value: 'a2b' },
    { label: 'Bulls', value: 'bulls' },
    { label: 'Charge', value: 'charge' },
    { label: 'Cube', value: 'cube' },
    { label: 'Faraday', value: 'faraday' },
    { label: 'Gazelle', value: 'gazelle' },
    { label: 'Haibike', value: 'haibike' },
    { label: 'Juiced', value: 'juiced' },
    { label: 'Kalkhoff', value: 'kalkhoff' },
    { label: 'Pedego', value: 'pedego' },
    { label: 'ProdecoTech', value: 'prodecotech' },
    { label: 'Raleigh', value: 'raleigh' },
    { label: 'Rad Power Bikes', value: 'rad_power_bikes' },
    { label: 'Ride1Up', value: 'ride1up' },
    { label: 'Riese & Müller', value: 'riese_muller' },
    { label: 'Specialized', value: 'specialized' },
    { label: 'Tern', value: 'tern' },
    { label: 'Trek', value: 'trek' },
    { label: 'Yamaha', value: 'yamaha' },
    { label: 'Blix', value: 'blix' },
    { label: 'Cannondale', value: 'cannondale' },
    { label: 'KBO', value: 'kbo' },
    { label: 'Magnum', value: 'magnum' },
    { label: 'Revel', value: 'revel' },
    { label: 'Velotric', value: 'velotric' },
    { label: 'Xtracycle', value: 'xtracycle' },
    { label: 'QuietKat', value: 'quietkat' },
    { label: 'Addmotor', value: 'addmotor' },
    { label: 'Ariel Rider', value: 'ariel_rider' },
    { label: 'Aventon', value: 'aventon' },
    { label: 'Bakcou', value: 'bakcou' },
    { label: 'Bintelli', value: 'bintelli' },
    { label: 'Brompton', value: 'brompton' },
    { label: 'DJ Bikes', value: 'dj_bikes' },
    { label: 'Ecotric', value: 'ecotric' },
    { label: 'Emojo', value: 'emojo' },
    { label: 'Engwe', value: 'engwe' },
    { label: 'Eunorau', value: 'eunorau' },
    { label: 'Evercross', value: 'evercross' },
    { label: 'Evelo', value: 'evelo' },
    { label: 'Eunorau', value: 'eunorau' },
    { label: 'G-Force', value: 'g_force' },
    { label: 'Gocycle', value: 'gocycle' },
    { label: 'Himiway', value: 'himiway' },
    { label: 'Juiced', value: 'juiced' },
    { label: 'KBO', value: 'kbo' },
    { label: 'Lectric', value: 'lectric' },
    { label: 'Magnum', value: 'magnum' },
    { label: 'Nakto', value: 'nakto' },
    { label: 'QuietKat', value: 'quietkat' },
    { label: 'Rad Power Bikes', value: 'rad_power_bikes' },
    { label: 'Ride1Up', value: 'ride1up' },
    { label: 'Riese & Müller', value: 'riese_muller' },
    { label: 'Sondors', value: 'sondors' },
    { label: 'Stark Drive', value: 'stark_drive' },
    { label: 'Swagtron', value: 'swagtron' },
    { label: 'Tern', value: 'tern' },
    { label: 'Trek', value: 'trek' },
    { label: 'Vanmoof', value: 'vanmoof' },
    { label: 'Vvolt', value: 'vvolt' },
    { label: 'Wing', value: 'wing' },
    { label: 'Xtracycle', value: 'xtracycle' },
    { label: 'Yamaha', value: 'yamaha' },
    { label: 'Zizzo', value: 'zizzo' },
    { label: 'Benno', value: 'benno' },
    { label: 'Batch', value: 'batch' },
    { label: 'Blix', value: 'blix' },
    { label: 'Breezer', value: 'breezer' },
    { label: 'Bulls', value: 'bulls' },
    { label: 'Cannondale', value: 'cannondale' },
    { label: 'Diamondback', value: 'diamondback' },
    { label: 'E-Joe', value: 'e_joe' },
    { label: 'Enzo', value: 'enzo' },
    { label: 'Eunorau', value: 'eunorau' },
    { label: 'Felt', value: 'felt' },
    { label: 'Flyer', value: 'flyer' },
    { label: 'Gazelle', value: 'gazelle' },
    { label: 'GenZe', value: 'genze' },
    { label: 'Giant', value: 'giant' },
    { label: 'GoCycle', value: 'gocycle' },
    { label: 'GreenBike', value: 'greenbike' },
    { label: 'GT', value: 'gt' },
    { label: 'Haibike', value: 'haibike' },
    { label: 'Haro', value: 'haro' },
    { label: 'Himiway', value: 'himiway' },
    { label: 'Hyper', value: 'hyper' },
    { label: 'iZip', value: 'izip' },
    { label: 'Juiced', value: 'juiced' },
    { label: 'Kalkhoff', value: 'kalkhoff' },
    { label: 'Kettler', value: 'kettler' },
    { label: 'Litespeed', value: 'litespeed' },
    { label: 'Marin', value: 'marin' },
    { label: 'Merida', value: 'merida' },
    { label: 'Mondraker', value: 'mondraker' },
    { label: 'Montague', value: 'montague' },
    { label: 'Moustache', value: 'moustache' },
    { label: 'NCM', value: 'ncm' },
    { label: 'Niner', value: 'niner' },
    { label: 'Noah’s Ark', value: 'noahs_ark' },
    { label: 'Norco', value: 'norco' },
    { label: 'Pinnacle', value: 'pinnacle' },
    { label: 'Pivot', value: 'pivot' },
    { label: 'Priority', value: 'priority' },
    { label: 'Propella', value: 'propella' },
    { label: 'Pure Cycles', value: 'pure_cycles' },
    { label: 'Rad', value: 'rad' },
    { label: 'Raleigh', value: 'raleigh' },
    { label: 'Revel', value: 'revel' },
    { label: 'Ride1Up', value: 'ride1up' },
    { label: 'Rockrider', value: 'rockrider' },
    { label: 'Rocky Mountain', value: 'rocky_mountain' },
    { label: 'Schwinn', value: 'schwinn' },
    { label: 'Sixthreezero', value: 'sixthreezero' },
    { label: 'Sondors', value: 'sondors' },
    { label: 'Specialized', value: 'specialized' },
    { label: 'Swagtron', value: 'swagtron' },
    { label: 'Trek', value: 'trek' },
    { label: 'Vanmoof', value: 'vanmoof' },
    { label: 'VoltBike', value: 'voltbike' },
    { label: 'Vvolt', value: 'vvolt' },
    { label: 'Watt', value: 'watt' },
    { label: 'Woom', value: 'woom' },
    { label: 'Yamaha', value: 'yamaha' },
    { label: 'Yeti', value: 'yeti' },
    { label: 'YT Industries', value: 'yt_industries' },
    { label: 'Zerode', value: 'zerode' },
    { label: 'Bianchi', value: 'bianchi' },
    { label: 'Brompton', value: 'brompton' },
    { label: 'Burley', value: 'burley' },
    { label: 'Cannondale', value: 'cannondale' },
    { label: 'Charge', value: 'charge' },
    { label: 'Civia', value: 'civia' },
    { label: 'Dahon', value: 'dahon' },
    { label: 'Dahon', value: 'dahon' },
    { label: 'Diamondback', value: 'diamondback' },
    { label: 'Electra', value: 'electra' },
    { label: 'Elliptigo', value: 'elliptigo' },
    { label: 'Evelo', value: 'evelo' },
    { label: 'Faraday', value: 'faraday' },
    { label: 'Gazelle', value: 'gazelle' },
    { label: 'Kona', value: 'kona' },
    { label: 'Tern', value: 'tern' },
    { label: 'Juiced', value: 'juiced' },
    { label: 'Priority', value: 'priority' },
    { label: 'Rad Power Bikes', value: 'rad_power_bikes' },
    { label: 'Salsa', value: 'salsa' },
    { label: 'Surly', value: 'surly' },
    { label: 'Yuba', value: 'yuba' },
    { label: 'Turner', value: 'turner' },
    { label: 'Woom', value: 'woom' },
    { label: 'Yeti Cycles', value: 'yeti_cycles' },
    { label: 'Zigo', value: 'zigo' },
    { label: 'Zobop', value: 'zobop' },
  ],
  // cycles end

  // for leisure boats and yachts
  boats: [
    { label: 'Aicon Yachts', value: 'aicon_yachts' },
    { label: 'Alen Yacht', value: 'alen_yacht' },
    { label: 'Alubat', value: 'alubat' },
    { label: 'American Tug', value: 'american_tug' },
    { label: 'Amels', value: 'amels' },
    { label: 'Anvera', value: 'anvera' },
    { label: 'Arcadia Yachts', value: 'arcadia_yachts' },
    { label: 'Arcona Yachts', value: 'arcona_yachts' },
    { label: 'Astondoa', value: 'astondoa' },
    { label: 'Axopar', value: 'axopar' },
    { label: 'Azimut Yachts', value: 'azimut_yachts' },
    { label: 'Baglietto', value: 'baglietto' },
    { label: 'Baja Marine', value: 'baja_marine' },
    { label: 'Bali Catamarans', value: 'bali_catamarans' },
    { label: 'Baltic Yachts', value: 'baltic_yachts' },
    { label: 'Bavaria Yachts', value: 'bavaria_yachts' },
    { label: 'Beneteau', value: 'beneteau' },
    { label: 'Bertram', value: 'bertram' },
    { label: 'Bering Yachts', value: 'bering_yachts' },
    { label: 'Bermuda Shipyard', value: 'bermuda_shipyard' },
    { label: 'Bluegame', value: 'bluegame' },
    { label: 'Boden Boatbuilding', value: 'boden_boatbuilding' },
    { label: 'Boston Whaler', value: 'boston_whaler' },
    { label: 'Broward Marine', value: 'broward_marine' },
    { label: 'Burger Boat Company', value: 'burger_boat_company' },
    {
      label: 'Camper & Nicholsons Yachts',
      value: 'camper_and_nicholsons_yachts',
    },
    { label: 'Canados', value: 'canados' },
    { label: 'Cape Dory', value: 'cape_dory' },
    { label: 'Carver Yachts', value: 'carver_yachts' },
    { label: 'Catana', value: 'catana' },
    { label: 'Catalina Yachts', value: 'catalina_yachts' },
    { label: 'Cayman Yachts', value: 'cayman_yachts' },
    { label: 'Chris-Craft', value: 'chris_craft' },
    { label: 'CNB Yachts', value: 'cnb_yachts' },
    { label: 'Codecasa', value: 'codecasa' },
    { label: 'Cobalt Boats', value: 'cobalt_boats' },
    { label: 'Cobia Boats', value: 'cobia_boats' },
    { label: 'Contest Yachts', value: 'contest_yachts' },
    { label: 'Couach Yachts', value: 'couach_yachts' },
    { label: 'Cruisers Yachts', value: 'cruisers_yachts' },
    { label: 'Custom Line', value: 'custom_line' },
    { label: 'Dale Sailing', value: 'dale_sailing' },
    { label: 'Damen Yachting', value: 'damen_yachting' },
    { label: 'Danforth Yachts', value: 'danforth_yachts' },
    { label: 'Dehler', value: 'dehler' },
    { label: 'Delphia Yachts', value: 'delphia_yachts' },
    { label: 'Delta Powerboats', value: 'delta_powerboats' },
    { label: 'Delta Marine', value: 'delta_marine' },
  ],
  // boats end

  // for charters
  charters: [
    { label: 'Beechcraft', value: 'beechcraft' },
    { label: 'Cessna', value: 'cessna' },
    { label: 'Pilatus Aircraft', value: 'pilatus_aircraft' },
    { label: 'Embraer', value: 'embraer' },
    { label: 'Gulfstream Aerospace', value: 'gulfstream_aerospace' },
    { label: 'Bombardier', value: 'bombardier' },
    { label: 'Dassault Aviation', value: 'dassault_aviation' },
    { label: 'Hawker Beechcraft', value: 'hawker_beechcraft' },
    { label: 'Piper Aircraft', value: 'piper_aircraft' },
    { label: 'Diamond Aircraft', value: 'diamond_aircraft' },
    { label: 'Cirrus Aircraft', value: 'cirrus_aircraft' },
    { label: 'Textron Aviation', value: 'textron_aviation' },
    { label: 'Epic Aircraft', value: 'epic_aircraft' },
    { label: 'Socata', value: 'socata' },
    { label: 'Honda Aircraft Company', value: 'honda_aircraft_company' },
    {
      label: 'Mooney International Corporation',
      value: 'mooney_international_corporation',
    },
    { label: 'Tecnam', value: 'tecnam' },
    { label: 'Eclipse Aerospace', value: 'eclipse_aerospace' },
    { label: 'Extra Flugzeugbau', value: 'extra_flugzeugbau' },
    { label: 'Daher', value: 'daher' },
    { label: 'Quest Aircraft Company', value: 'quest_aircraft_company' },
    { label: 'Viking Air', value: 'viking_air' },
    { label: 'Lancair International', value: 'lancair_international' },
    { label: 'AeroEast Europe', value: 'aeroeast_europe' },
    { label: 'Avanti Aviation', value: 'avanti_aviation' },
    { label: 'JMB Aircraft', value: 'jmb_aircraft' },
    { label: 'Pacific Aerospace', value: 'pacific_aerospace' },
    { label: 'Vulcanair', value: 'vulcanair' },
    { label: 'GippsAero', value: 'gippsaero' },
    { label: 'Air Tractor', value: 'air_tractor' },
    { label: 'Zlin Aviation', value: 'zlin_aviation' },
    { label: 'Mahindra Aerospace', value: 'mahindra_aerospace' },
    { label: 'Grob Aircraft', value: 'grob_aircraft' },
    { label: 'Adam Aircraft Industries', value: 'adam_aircraft_industries' },
    { label: 'Shark Aero', value: 'shark_aero' },
    { label: 'Aerostar Aircraft', value: 'aerostar_aircraft' },
    { label: 'Blackshape Aircraft', value: 'blackshape_aircraft' },
    { label: 'Bristell Aircraft', value: 'bristell_aircraft' },
    { label: 'Alpi Aviation', value: 'alpi_aviation' },
    { label: 'Viper Aircraft', value: 'viper_aircraft' },
    { label: 'Flight Design', value: 'flight_design' },
    { label: 'Pipistrel', value: 'pipistrel' },
    { label: 'Glasair Aviation', value: 'glasair_aviation' },
    {
      label: 'Robinson Helicopter Company',
      value: 'robinson_helicopter_company',
    },
    { label: 'Kodiak Aircraft Company', value: 'kodiak_aircraft_company' },
    { label: 'Aerospool', value: 'aerospool' },
    { label: 'Rans Designs', value: 'rans_designs' },
    { label: 'SkyReach Aircraft', value: 'skyreach_aircraft' },
    { label: 'Just Aircraft', value: 'just_aircraft' },
    { label: 'Kitfox Aircraft', value: 'kitfox_aircraft' },
  ],
  // charters end
}
