export const bikeData = [
    { label: 'Adiva', value: 'adiva' },
    { label: 'Aeon Motor', value: 'aeonmotor' },
    { label: 'AJP', value: 'ajp' },
    { label: 'Alta Motors', value: 'altamotors' },
    { label: 'Ampere Vehicles', value: 'amperevehicles' },
    { label: 'Aprilia', value: 'aprilia' },
    { label: 'Arcimoto', value: 'arcimoto' },
    { label: 'Arctic Cat', value: 'arcticcat' },
    { label: 'Ariel Motorcycles', value: 'arielmotorcycles' },
    { label: 'Askoll', value: 'askoll' },
    { label: 'Ather Energy', value: 'atherenergy' },
    { label: 'Atumobile', value: 'atumobile' },
    { label: 'Bajaj Auto', value: 'bajajauto' },
    { label: 'Benelli', value: 'benelli' },
    { label: 'Benelli Q.J.', value: 'benelliqj' },
    { label: 'Beta Motor', value: 'betamotor' },
    { label: 'Beta Motorcycles', value: 'betamotorcycles' },
    { label: 'Big Dog Motorcycles', value: 'bigdogmotorcycles' },
    { label: 'Bimota', value: 'bimota' },
    { label: 'Bombardier Recreational Products (BRP)', value: 'brp' },
    { label: 'Borile', value: 'borile' },
    { label: 'Brammo', value: 'brammo' },
    { label: 'Brixton Motorcycles', value: 'brixtonmotorcycles' },
    { label: 'Brough Superior', value: 'broughsuperior' },
    {
      label: 'Brutus Electric Motorcycles',
      value: 'brutuselectricmotorcycles',
    },
    { label: 'Brutus Motorcycles', value: 'brutusmotorcycles' },
    { label: 'BSA', value: 'bsa' },
    { label: 'BSA Motorcycles', value: 'bsamotorcycles' },
    { label: 'Bultaco', value: 'bultaco' },
    { label: 'Cake', value: 'cake' },
    { label: 'Can-Am', value: 'canam' },
    { label: 'Cectek', value: 'cectek' },
    { label: 'CF Moto', value: 'cfmoto' },
    { label: 'CFMoto', value: 'cfmoto' },
    { label: 'Christini', value: 'christini' },
    { label: 'Cleveland CycleWerks', value: 'clevelandcyclewerks' },
    { label: 'Cobra Motorcycles', value: 'cobramotorcycles' },
    { label: 'Confederate Motors', value: 'confederatemotors' },
    { label: 'Curtiss', value: 'curtiss' },
    { label: 'Curtiss Motorcycles', value: 'curtissmotorcycles' },
    { label: 'Cushman', value: 'cushman' },
    { label: 'Dab Motors', value: 'dabmotors' },
    { label: 'Daelim', value: 'daelim' },
    { label: 'Dahon', value: 'dahon' },
    { label: 'Damon Motors', value: 'damonmotors' },
    { label: 'Derbi', value: 'derbi' },
    { label: 'Desmo', value: 'desmo' },
    { label: 'Dino Bikes', value: 'dinobikes' },
    { label: 'Ducati', value: 'ducati' },
    { label: 'EeVe India', value: 'eeveindia' },
    { label: 'Elio Motors', value: 'eliomotors' },
    { label: 'Emflux Motors', value: 'emfluxmotors' },
    { label: 'E-Moto Tech', value: 'emototech' },
    { label: 'Energica', value: 'energica' },
    { label: 'Evoke Motorcycles', value: 'evokemotorcycles' },
    { label: 'Excelsior-Henderson', value: 'excelsiorhenderson' },
    { label: 'Fantasia', value: 'fantasia' },
    { label: 'Fantic Motor', value: 'fanticmotor' },
    { label: 'Feishen Group', value: 'feishengroup' },
    { label: 'Flying Tiger', value: 'flyingtiger' },
    { label: 'Fuell', value: 'fuell' },
    { label: 'Fuzion Scooters', value: 'fuzionscooters' },
    { label: 'Geely', value: 'geely' },
    { label: 'Genuine Scooters', value: 'genuinescooters' },
    { label: 'Gilera', value: 'gilera' },
    { label: 'Gogoro', value: 'gogoro' },
    { label: 'Gordon Murray', value: 'gordonmurray' },
    { label: 'Gravton Motors', value: 'gravtonmotors' },
    { label: 'Greaves Cotton', value: 'greavescotton' },
    { label: 'Green Vehicles', value: 'greenvehicles' },
    { label: 'Haojue', value: 'haojue' },
    { label: 'Harley-Davidson', value: 'harleydavidson' },
    { label: 'Heinkel', value: 'heinkel' },
    { label: 'Hercules', value: 'hercules' },
    { label: 'Hero Electric', value: 'heroelectric' },
    { label: 'Hero MotoCorp', value: 'heromotocorp' },
    { label: 'Hesketh Motorcycles', value: 'heskethmotorcycles' },
    { label: 'Hildebrand & Wolfmüller', value: 'hildebrandwolfmuller' },
    { label: 'Honda', value: 'honda' },
    { label: 'Horex', value: 'horex' },
    { label: 'Husaberg', value: 'husaberg' },
    { label: 'Husqvarna', value: 'husqvarna' },
    { label: 'Husqvarna Motorcycles', value: 'husqvarnamotorcycles' },
    { label: 'Hyosung', value: 'hyosung' },
    { label: 'Indian Motorcycle', value: 'indianmotorcycle' },
    { label: 'Italika', value: 'italika' },
    { label: 'Italjet', value: 'italjet' },
    { label: 'Jannarelly', value: 'jannarelly' },
    { label: 'Janus Motorcycles', value: 'janusmotorcycles' },
    { label: 'Jawa', value: 'jawa' },
    { label: 'Jianshe', value: 'jianshe' },
    { label: 'Jinbei', value: 'jinbei' },
    { label: 'Jonway', value: 'jonway' },
    { label: 'Keeway', value: 'keeway' },
    {
      label: 'Kinetic Green Energy & Power Solutions',
      value: 'kineticgreenenergypowersolutions',
    },
    { label: 'KTM', value: 'ktm' },
    { label: 'Kuberg', value: 'kuberg' },
    { label: 'Kumpan Electric', value: 'kumpanelectric' },
    { label: 'Kymco', value: 'kymco' },
    { label: 'Lambretta', value: 'lambretta' },
    { label: 'Lance', value: 'lance' },
    { label: 'Laraki', value: 'laraki' },
    { label: 'Laverda', value: 'laverda' },
    { label: 'Lexmoto', value: 'lexmoto' },
    { label: 'Lifan', value: 'lifan' },
    { label: 'Liger Mobility', value: 'ligermobility' },
    { label: 'Lightning Motorcycles', value: 'lightningmotorcycles' },
    { label: 'Loncin', value: 'loncin' },
    { label: 'Lotus Cars', value: 'lotuscars' },
    { label: 'Lucra Cars', value: 'lucracars' },
    { label: 'Mac Motorcycles', value: 'macmotorcycles' },
    { label: 'Mahindra Two Wheelers', value: 'mahindratwowheelers' },
    { label: 'Malaguti', value: 'malaguti' },
    { label: 'Mavizen', value: 'mavizen' },
    { label: 'MBK', value: 'mbk' },
    { label: 'Modenas', value: 'modenas' },
    { label: 'Moto Guzzi', value: 'motoguzzi' },
    { label: 'Moto Morini', value: 'motomorini' },
    { label: 'Motobécane', value: 'motobecane' },
    { label: 'Motobi', value: 'motobi' },
    { label: 'MotoCzysz', value: 'motoczysz' },
    { label: 'MotoRoyale', value: 'motoroyale' },
    { label: 'MV Agusta', value: 'mvagusta' },
    { label: 'MZ', value: 'mz' },
    { label: 'Naza', value: 'naza' },
    { label: 'NIU', value: 'niu' },
    { label: 'Norton Motorcycle Company', value: 'nortonmotorcyclecompany' },
    { label: 'Okaya Electric', value: 'okayaelectric' },
    { label: 'Okinawa Autotech', value: 'okinawaautotech' },
    { label: 'Ola Electric', value: 'olaelectric' },
    { label: 'One Moto', value: 'onemoto' },
    { label: 'Oset Bikes', value: 'osetbikes' },
    { label: 'Paton', value: 'paton' },
    { label: 'Peugeot', value: 'peugeot' },
    { label: 'Peugeot Motocycles', value: 'peugeotmotocycles' },
    { label: 'PGO Scooters', value: 'pgoscooters' },
    { label: 'Piaggio', value: 'piaggio' },
    { label: 'Polaris', value: 'polaris' },
    { label: 'PURE EV', value: 'pureev' },
    { label: 'Qianjiang', value: 'qianjiang' },
    { label: 'QJMotor', value: 'qjmotor' },
    { label: 'Rad Power Bikes', value: 'radpowerbikes' },
    { label: 'Raleigh', value: 'raleigh' },
    { label: 'Revolt Motors', value: 'revoltmotors' },
    { label: 'Rieju', value: 'rieju' },
    { label: 'Rimac Automobili', value: 'rimacautomobili' },
    { label: 'Rokon', value: 'rokon' },
    { label: 'Royal Alloy', value: 'royalalloy' },
    { label: 'Royal Enfield', value: 'royalenfield' },
    { label: 'Rudge-Whitworth', value: 'rudgewhitworth' },
    { label: 'Scomadi', value: 'scomadi' },
    { label: 'Scorpa', value: 'scorpa' },
    {
      label: 'Scuderia Cameron Glickenhaus',
      value: 'scuderiacameronglickenhaus',
    },
    { label: 'Senke', value: 'senke' },
    { label: 'Sherco', value: 'sherco' },
    { label: 'SIMI', value: 'simi' },
    { label: 'Simple Energy', value: 'simpleenergy' },
    { label: 'Skyteam', value: 'skyteam' },
    { label: 'SMC', value: 'smc' },
    { label: 'Stromer', value: 'stromer' },
    { label: 'Sukida', value: 'sukida' },
    { label: 'Sundiro Honda', value: 'sundirohonda' },
    { label: 'Sunra', value: 'sunra' },
    { label: 'Super Soco', value: 'supersoco' },
    { label: 'Suzuki', value: 'suzuki' },
    { label: 'SWM', value: 'swm' },
    { label: 'SYM', value: 'sym' },
    { label: 'Tacita', value: 'tacita' },
    { label: 'Tai Ling', value: 'tailing' },
    { label: 'Tarform', value: 'tarform' },
    { label: 'Techrules', value: 'techrules' },
    { label: 'TGB', value: 'tgb' },
    { label: 'Tomos', value: 'tomos' },
    { label: 'Tork Motors', value: 'torkmotors' },
    { label: 'Triumph', value: 'triumph' },
    { label: 'Triumph Motorcycles', value: 'triumphmotorcycles' },
    { label: 'TVS Motor Company', value: 'tvsmotorcompany' },
    { label: 'Ultraviolette Automotive', value: 'ultravioletteautomotive' },
    { label: 'UM Motorcycles', value: 'ummotorcycles' },
    { label: 'Urban Arrow', value: 'urbanarrow' },
    { label: 'Vectrix', value: 'vectrix' },
    { label: 'Vespa', value: 'vespa' },
    { label: 'Voge', value: 'voge' },
    { label: 'Volcon', value: 'volcon' },
    { label: 'Volt Motorbikes', value: 'voltmotorbikes' },
    { label: 'Voxan', value: 'voxan' },
    { label: 'War Horse', value: 'warhorse' },
    { label: 'Wottan Motor', value: 'wottanmotor' },
    { label: 'Xingyue', value: 'xingyue' },
    { label: 'Xootr', value: 'xootr' },
    { label: 'Yamaha', value: 'yamaha' },
    { label: 'Yezdi', value: 'yezdi' },
    { label: 'Zero Engineering', value: 'zeroengineering' },
    { label: 'Zero Motorcycles', value: 'zeromotorcycles' },
    { label: 'ZEV', value: 'zev' },
    { label: 'Znen', value: 'znen' },
    { label: 'Zongshen', value: 'zongshen' },
    { label: 'Zontes', value: 'zontes' },
  ]