export const boatsData = [
    { label: 'AB Yachts', value: 'abyachts' },
    { label: 'Absolute Yachts', value: 'absoluteyachts' },
    { label: 'Acico Yachts', value: 'acicoyachts' },
    { label: 'Admiral Yachts', value: 'admiralyachts' },
    { label: 'Advance Yachts', value: 'advanceyachts' },
    { label: 'Advanced Yachts', value: 'advancedyachts' },
    { label: 'Aegean Yachts', value: 'aegeanyachts' },
    { label: 'Aicon Yachts', value: 'aiconyachts' },
    { label: 'Akerboom Yacht Equipment', value: 'akerboomyachtequipment' },
    { label: 'Alaska Yachts', value: 'alaskayachts' },
    { label: 'Alaskan Yachts', value: 'alaskanyachts' },
    { label: 'Alen Yacht', value: 'alenyacht' },
    { label: 'Alubat', value: 'alubat' },
    { label: 'Alumarine Shipyard', value: 'alumarineshipyard' },
    { label: 'Alva Yachts', value: 'alvayachts' },
    { label: 'Alyssa Yachts', value: 'alyssayachts' },
    { label: 'Amasea Yachts', value: 'amaseayachts' },
    { label: 'Amels', value: 'amels' },
    { label: 'Amer Yachts', value: 'ameryachts' },
    { label: 'American Marine', value: 'americanmarine' },
    { label: 'American Tug', value: 'americantug' },
    { label: 'Anka Yachts', value: 'ankayachts' },
    { label: 'Anselmi Boretti', value: 'anselmiboretti' },
    { label: 'Antigua Yachts', value: 'antiguayachts' },
    { label: 'Anvera', value: 'anvera' },
    { label: 'Aqua Spirit', value: 'aquaspirit' },
    { label: 'Aquila Power Catamarans', value: 'aquilapowercatamarans' },
    { label: 'Arcadia Yachts', value: 'arcadiayachts' },
    { label: 'Arcona Yachts', value: 'arconayachts' },
    { label: 'Aresa Yachts', value: 'aresayachts' },
    { label: 'Art of Kinetik', value: 'artofkinetik' },
    { label: 'Astondoa', value: 'astondoa' },
    { label: 'Atlantis Yachts', value: 'atlantisyachts' },
    { label: 'Aventura Catamarans', value: 'aventuracatamarans' },
    { label: 'Axopar', value: 'axopar' },
    { label: 'Azimut Yachts', value: 'azimutyachts' },
    { label: 'Baglietto', value: 'baglietto' },
    { label: 'Baglietto Yachts', value: 'bagliettoyachts' },
    { label: 'Baia Yachts', value: 'baiayachts' },
    { label: 'Baja Marine', value: 'bajamarine' },
    { label: 'Bali Catamarans', value: 'balicatamarans' },
    { label: 'Baltic Yachts', value: 'balticyachts' },
    { label: 'Bandido Yachts', value: 'bandidoyachts' },
    { label: 'Barbican Yachts', value: 'barbicanyachts' },
    { label: 'Barker Boatworks', value: 'barkerboatworks' },
    { label: 'Barracuda Yachts', value: 'barracudayachts' },
    { label: 'Baumarine', value: 'baumarine' },
    { label: 'Bavaria Yachts', value: 'bavariayachts' },
    { label: 'Beneteau', value: 'beneteau' },
    { label: 'Benetti Yachts', value: 'benettiyachts' },
    { label: 'Bering Yachts', value: 'beringyachts' },
    { label: 'Bermuda Shipyard', value: 'bermudashipyard' },
    { label: 'Bertram', value: 'bertram' },
    { label: 'Bertram Yachts', value: 'bertramyachts' },
    { label: 'Bilgin Yachts', value: 'bilginyachts' },
    { label: 'Billionaire Yachts', value: 'billionaireyachts' },
    { label: 'Black Pearl Yachts', value: 'blackpearlyachts' },
    { label: 'Black Sea Yachts', value: 'blackseayachts' },
    { label: 'Blizzard Yachts', value: 'blizzardyachts' },
    { label: 'Bloemsma Van Breemen', value: 'bloemsmavanbreemen' },
    { label: 'Blount Boats', value: 'blountboats' },
    { label: 'Bluegame', value: 'bluegame' },
    { label: 'Bluewater Yachts', value: 'bluewateryachts' },
    { label: 'Boarncruiser', value: 'boarncruiser' },
    { label: 'Boden Boatbuilding', value: 'bodenboatbuilding' },
    { label: 'Boesch Boats', value: 'boeschboats' },
    { label: 'Boksa Marine Design', value: 'boksamarinedesign' },
    { label: 'Bondway Yachts', value: 'bondwayyachts' },
    { label: 'Boston Whaler', value: 'bostonwhaler' },
    { label: 'Bowa Yachts', value: 'bowayachts' },
    { label: 'Brabus Marine', value: 'brabusmarine' },
    { label: 'Bravo Yachts', value: 'bravoyachts' },
    { label: 'Broadblue Catamarans', value: 'broadbluecatamarans' },
    { label: 'Broom Boats', value: 'broomboats' },
    { label: 'Broward Marine', value: 'browardmarine' },
    { label: 'Bruckmann Yachts', value: 'bruckmannyachts' },
    { label: 'Buccaneer Yachts', value: 'buccaneeryachts' },
    { label: 'Burger Boat Company', value: 'burgerboatcompany' },
    { label: 'Cabin Fever', value: 'cabinfever' },
    { label: 'Caliber Yachts', value: 'caliberyachts' },
    { label: 'Californian Yachts', value: 'californianyachts' },
    { label: 'Calm Waters', value: 'calmwaters' },
    { label: 'Camper & Nicholsons Yachts', value: 'campernicholsonsyachts' },
    { label: 'Canados', value: 'canados' },
    { label: 'Canados Yachts', value: 'canadosyachts' },
    { label: 'Cantiere delle Marche', value: 'cantieredellemarche' },
    { label: 'Cape Dory', value: 'capedory' },
    { label: 'Cape Dory Yachts', value: 'capedoryyachts' },
    { label: 'Capri Yachts', value: 'capriyachts' },
    { label: 'Caravelle Boats', value: 'caravelleboats' },
    { label: 'Caribbean Yacht', value: 'caribbeanyacht' },
    { label: 'Caribbean Yachts', value: 'caribbeanyachts' },
    { label: 'Carlini Shipyard', value: 'carlinishipyard' },
    { label: 'Carter Yachts', value: 'carteryachts' },
    { label: 'Carver Yachts', value: 'carveryachts' },
    { label: 'Catalina Yachts', value: 'catalinayachts' },
    { label: 'Catana', value: 'catana' },
    { label: 'Catana Catamarans', value: 'catanacatamarans' },
    { label: 'Catari Yachts', value: 'catariyachts' },
    { label: 'Cayman Yachts', value: 'caymanyachts' },
    { label: 'C-Catamarans', value: 'ccatamarans' },
    { label: 'Centaur Yachts', value: 'centauryachts' },
    { label: 'Challenger Yachts', value: 'challengeryachts' },
    { label: 'Chaparral Boats', value: 'chaparralboats' },
    { label: 'Cheoy Lee', value: 'cheoylee' },
    { label: 'Cheoy Lee Shipyards', value: 'cheoyleeshipyards' },
    { label: 'Chris-Craft', value: 'chriscraft' },
    { label: 'Christensen Yachts', value: 'christensenyachts' },
    { label: 'Chrysler Marine', value: 'chryslermarine' },
    { label: 'Cimitarra Yachts', value: 'cimitarra' },
    { label: 'Claasen Shipyard', value: 'claasenshipyard' },
    { label: 'Classic Yachts', value: 'classicyachts' },
    { label: 'CNB Yachts', value: 'cnbyachts' },
    { label: 'Cobalt Boats', value: 'cobaltboats' },
    { label: 'Cobia Boats', value: 'cobiaboats' },
    { label: 'Cockwells', value: 'cockwells' },
    { label: 'Cocoa Yachts', value: 'cocoayachts' },
    { label: 'Code Yachts', value: 'codeyachts' },
    { label: 'Codecasa', value: 'codecasa' },
    { label: 'Codecasa Yachts', value: 'codecasayachts' },
    { label: 'Comar Yachts', value: 'comaryachts' },
    { label: 'Compass Yachts', value: 'compassyachts' },
    { label: 'Concorde Yachts', value: 'concordeyachts' },
    { label: 'Contest Yachts', value: 'contestyachts' },
    { label: 'Conyplex', value: 'conyplex' },
    { label: 'Couach Yachts', value: 'couachyachts' },
    { label: 'Cranchi Yachts', value: 'cranchiyachts' },
    { label: 'Creative Yachts', value: 'creativeyachts' },
    { label: 'Crickett Yachts', value: 'crickettyachts' },
    { label: 'Cris-Craft Yachts', value: 'criscraftyachts' },
    { label: 'Cromarty Yachts', value: 'cromartyyachts' },
    { label: 'Cruisers Yachts', value: 'cruisersyachts' },
    { label: 'Cumberland Yachts', value: 'cumberlanyachts' },
    { label: 'Custom Line', value: 'customline' },
    { label: 'Custom Line Yachts', value: 'customlineyachts' },
    { label: 'Cutter Marine Yachts', value: 'cuttermarineyachts' },
    { label: 'Dale Sailing', value: 'dalesailing' },
    { label: 'Dalla Pieta Yachts', value: 'dallapietayachts' },
    { label: 'Damen Yachting', value: 'damenyachting' },
    { label: 'Danforth Yachts', value: 'danforthyachts' },
    { label: 'Dariel Yachts', value: 'darielyachts' },
    { label: 'David Marlow Yachts', value: 'davidmarlow' },
    { label: 'Dazcat', value: 'dazcat' },
    { label: 'De Vries Lentsch Yachts', value: 'devrieslentschyachts' },
    { label: 'Dehler', value: 'dehler' },
    { label: 'Dehler Yachts', value: 'dehleryachts' },
    { label: 'Delphia Yachts', value: 'delphiayachts' },
    { label: 'Delta Marine', value: 'deltamarine' },
    { label: 'Delta Powerboats', value: 'deltapowerboats' },
    { label: 'Design Craft', value: 'designcraft' },
    { label: 'Discovery Yachts', value: 'discoveryyachts' },
    { label: 'Dixon Yacht Design', value: 'dixonyachtdesign' },
    { label: 'Doggersbank', value: 'doggersbank' },
    { label: 'Dominator', value: 'dominator' },
    { label: 'Dominator Yachts', value: 'dominatoryachts' },
    { label: 'Donzi Yachts', value: 'donziyachts' },
    { label: 'Doral Yachts', value: 'doralyachts' },
    { label: 'Drettmann Yachts', value: 'drettmannyachts' },
    { label: 'Dufour Yachts', value: 'dufouryachts' },
    { label: 'DutchCraft', value: 'dutchcraft' },
    { label: 'DutchCraft Yachts', value: 'dutchcraftyachts' },
    { label: 'Dyna Yachts', value: 'dynayachts' },
    { label: 'Dynamiq', value: 'dynamiq' },
    { label: 'Dynamiq Yachts', value: 'dynamiqyachts' },
    { label: 'Eagle Marine', value: 'eaglemarine' },
    { label: 'Eastbay Yachts', value: 'eastbayyachts' },
    { label: 'Easystreet Yachts', value: 'easystreetyachts' },
    { label: 'Edgewater Power Boats', value: 'edgewaterpowerboats' },
    { label: 'Elan Yachts', value: 'elanyachts' },
    { label: 'Elandra Yachts', value: 'elandrayachts' },
    { label: 'Elegance Yachts', value: 'eleganceyachts' },
    { label: 'Element Yachts', value: 'elementyachts' },
    { label: 'Elling Yachts', value: 'ellingyachts' },
    { label: 'Endurance Yachts', value: 'enduranceyachts' },
    { label: 'Epic Yachts', value: 'epicyachts' },
    { label: 'Eros Yachts', value: 'erosyachts' },
    { label: 'Evo Yachts', value: 'evoyachts' },
    { label: 'Explorer Yachts', value: 'exploreryachts' },
    { label: 'Extravagant Yachts', value: 'extravagantyachts' },
    { label: 'EYC Yachts', value: 'eycyachts' },
    { label: 'Fairline Yachts', value: 'fairlineyachts' },
    { label: 'Falcon Yachts', value: 'falconyachts' },
    { label: 'Feadship', value: 'feadship' },
    { label: 'Feeling Yachts', value: 'feelingyachts' },
    { label: 'Ferretti Yachts', value: 'ferrettiyachts' },
    { label: 'Fipa Group', value: 'fipagroup' },
    { label: 'Fitzroy Yachts', value: 'fitzroyyachts' },
    { label: 'Fjord Boats', value: 'fjordboats' },
    { label: 'Fjord Yachts', value: 'fjordyachts' },
    { label: 'Fleming Yachts', value: 'flemingyachts' },
    { label: 'Floating Life', value: 'floatinglife' },
    { label: 'Formula Boats', value: 'formulaboats' },
    { label: 'Fountaine Pajot', value: 'fountainepajot' },
    { label: 'Fraser Yachts', value: 'fraseryachts' },
    { label: 'Freedom Yachts', value: 'freedomyachts' },
    { label: 'Frers Naval Architecture', value: 'frersnavalarchitecture' },
    { label: 'Fusion Yachts', value: 'fusionyachts' },
    { label: 'Gabriella Yachts', value: 'gabriellayachts' },
    { label: 'Galeon Yachts', value: 'galeonyachts' },
    { label: 'Garcia Yachts', value: 'garciayachts' },
    { label: 'Garda Yachts', value: 'gardayachts' },
    { label: 'Gaspard Yachts', value: 'gaspardyachts' },
    { label: 'Gemini Yachts', value: 'geminiyachts' },
    { label: 'Gianetti Yachts', value: 'gianettiyachts' },
    { label: 'Gigantic Yachts', value: 'giganticyachts' },
    { label: 'Glastron', value: 'glastron' },
    { label: 'Glastron Yachts', value: 'glastronyachts' },
    { label: 'Gleam Yachts', value: 'gleamyachts' },
    { label: 'Glider Yachts', value: 'glideryachts' },
    { label: 'Gold Coast Yachts', value: 'goldcoastyachts' },
    { label: 'Goldfish Boat', value: 'goldfishboat' },
    { label: 'Grand Banks', value: 'grandbanks' },
    { label: 'Grand Banks Yachts', value: 'grandbanksyachts' },
    { label: 'Greenline Yachts', value: 'greenlineyachts' },
    { label: 'Gulet Yachts', value: 'guletyachts' },
    { label: 'Gulf Craft', value: 'gulfcraft' },
    { label: 'Hallberg-Rassy', value: 'hallbergrassy' },
    { label: 'Hallberg-Rassy Yachts', value: 'hallbergrassyachts' },
    { label: 'Hamble Yachts', value: 'hambleyachts' },
    { label: 'Hampton Yachts', value: 'hamptonyachts' },
    { label: 'Hanse Yachts', value: 'hanseyachts' },
    { label: 'Hardy Marine', value: 'hardymarine' },
    { label: 'Hatteras Yachts', value: 'hatterasyachts' },
    { label: 'Heesen Yachts', value: 'heesen' },
    { label: 'Helleman Yachts', value: 'helleman' },
    { label: 'Helmsman Trawlers', value: 'helmsmantrawlers' },
    { label: 'Hinckley Yachts', value: 'hinckleyyachts' },
    { label: 'Holland Yachts', value: 'hollandyachts' },
    { label: 'Horizon Yachts', value: 'horizonyachts' },
    { label: 'Hunter Marine', value: 'huntermarine' },
    { label: 'Hurricane Yachts', value: 'hurricaneyachts' },
    { label: 'Hylas Yachts', value: 'hylasyachts' },
    { label: 'IAG Yachts', value: 'iagyachts' },
    { label: 'IC Frantise', value: 'icfrantise' },
    { label: 'ICON Yachts', value: 'iconyachts' },
    { label: 'ILC Yachts', value: 'ilcyachts' },
    { label: 'Impact Marine', value: 'impactmarine' },
    { label: 'IMPERIAL Yachts', value: 'imperialyachts' },
    { label: 'Inace Yachts', value: 'inaceyachts' },
    { label: 'Incat Crowther', value: 'incatcrowther' },
    { label: 'Indigo Yachts', value: 'indigoyachts' },
    { label: 'Interlude Yachts', value: 'interludeyachts' },
    { label: 'Intermarine Yachts', value: 'intermarineyachts' },
    { label: 'Invincible Boats', value: 'invincibleboats' },
    { label: 'Invision Yachts', value: 'invisionyachts' },
    { label: 'Island Packet Yachts', value: 'islandpacketyachts' },
    { label: 'Island Yachts', value: 'islandyachts' },
    { label: 'Italcraft Yachts', value: 'italcraftyachts' },
    { label: 'Itama Yachts', value: 'itamayachts' },
    { label: 'Izar Yachts', value: 'izaryachts' },
    { label: 'J Boats', value: 'jboats' },
    { label: 'J Craft Boats', value: 'jcraftboats' },
    { label: 'J/Boats', value: 'jboats' },
    { label: 'Jacaranda Yachts', value: 'jacarandayachts' },
    { label: 'Jeanneau', value: 'jeanneau' },
    { label: 'Jeanneau Yachts', value: 'jeanneauyachts' },
    { label: 'Jersey Yachts', value: 'jerseyyachts' },
    { label: 'JFA Yachts', value: 'jfayachts' },
    { label: 'Johnson Yachts', value: 'johnsonyachts' },
    { label: 'Jones Yachts', value: 'jonesyachts' },
    { label: 'Jongert', value: 'jongert' },
    { label: 'Jongert Yachts', value: 'jongertyachts' },
    { label: 'Kadey-Krogen Yachts', value: 'kadeykrogenyachts' },
    { label: 'KaiserWerft', value: 'kaiserwerft' },
    { label: 'KaiserWerft Yachts', value: 'kaiserwerftyachts' },
    { label: 'Kanasa Yachts', value: 'kanasayachts' },
    { label: 'Kanter Yachts', value: 'kanteryachts' },
    { label: 'Kenai Yachts', value: 'kenaiyachts' },
    { label: 'King Marine', value: 'kingmarine' },
    { label: 'Kingship Yachts', value: 'kingshipyachts' },
    { label: 'Kleven Yachts', value: 'klevenyachts' },
    { label: 'Kneissl Yachts', value: 'kneisslyachts' },
    { label: 'Kok Yachts', value: 'kokyachts' },
    { label: 'Kokomo Yachts', value: 'kokomoyachts' },
    { label: 'Koray Yachts', value: 'korayyachts' },
    { label: 'Kremer Yachts', value: 'kremeryachts' },
    { label: 'Lagoon Catamarans', value: 'lagooncatamarans' },
    { label: 'LAGOON Yachts', value: 'lagoonyachts' },
    { label: 'Lakyverf Yachts', value: 'lakyverfyachts' },
    { label: 'Lang Yachts', value: 'langyachts' },
    { label: 'Lazzara Yachts', value: 'lazzarayachts' },
    { label: 'Leonard Yachts', value: 'leonardyachts' },
    { label: 'Leopard Catamarans', value: 'leopardcatamarans' },
    { label: 'Les Lianes Yachts', value: 'leslianesyachts' },
    { label: 'Levante Yachts', value: 'levanteyachts' },
    { label: 'Lewmar Yachts', value: 'lewmaryachts' },
    { label: 'Lexus Yachts', value: 'lexusyachts' },
    { label: 'Lighthouse Yachts', value: 'lighthouseyachts' },
    { label: 'Lilybaeum Yachts', value: 'lilybaeumyachts' },
    { label: 'Linssen Yachts', value: 'linssenyachts' },
    { label: 'Liquid Yachts', value: 'liquidyachts' },
    { label: 'Lister Yachts', value: 'listeryachts' },
    { label: 'Living Yachts', value: 'livingyachts' },
    { label: 'Lloyd Yachts', value: 'lloydyachts' },
    { label: 'Lürssen', value: 'lurssen' },
    { label: 'Lürssen Yachts', value: 'lurssenyachts' },
    { label: 'Lynx Yachts', value: 'lynxyachts' },
    { label: 'M/Y Yachts', value: 'myyachts' },
    { label: 'Macann Yachts', value: 'macannyachts' },
    { label: 'Macgregor Yachts', value: 'macgregoryachts' },
    { label: 'Mackay Yachts', value: 'mackayyachts' },
    { label: 'Mader Yachts', value: 'maderyachts' },
    { label: 'Magellano Yachts', value: 'magellanoyachts' },
    { label: 'Magma Yachts', value: 'magmayachts' },
    { label: 'Magnum Marine', value: 'magnummarine' },
    { label: 'Maine Cat', value: 'mainecat' },
    { label: 'Maori Yachts', value: 'maoriyachts' },
    { label: 'Marell Boats', value: 'marellboats' },
    { label: 'Marina Boats', value: 'marinaboats' },
    { label: 'Marine Group Boat Works', value: 'marinegroupboatworks' },
    { label: 'Marine Trader Yachts', value: 'marinetraderyachts' },
    { label: 'Marinette Yachts', value: 'marinetteyachts' },
    { label: 'Marlow Explorer', value: 'marlowexplorer' },
    { label: 'Marlow Yachts', value: 'marlowyachts' },
    { label: 'Marlow-Hunter', value: 'marlowhunter' },
    { label: 'Marquis Yachts', value: 'marquisyachts' },
    { label: 'Marquis-Larson Group', value: 'marquislarsongroup' },
    { label: 'Marten Yachts', value: 'martenyachts' },
    { label: 'Massimo Yachts', value: 'massimoyachts' },
    { label: 'Master Yachts', value: 'masteryachts' },
    { label: 'MasterCraft', value: 'mastercraft' },
    { label: 'Mathew Yachts', value: 'mathewyachts' },
    { label: 'Maverick Yachts', value: 'maverickyachts' },
    { label: 'Maxi Yachts', value: 'maxiyachts' },
    { label: 'Mengi Yay Yachts', value: 'mengiyayyachts' },
    { label: 'Meridian Yachts', value: 'meridianyachts' },
    { label: 'Michelin Yachts', value: 'michelinyachts' },
    { label: 'Midland Yachts', value: 'midlandyachts' },
    { label: 'Mikros Yachts', value: 'mikrosyachts' },
    { label: 'Moana Yachts', value: 'moanayachts' },
    { label: 'Moggs Yachts', value: 'moggsyachts' },
    { label: 'Monte Carlo Yachts', value: 'montecarloyachts' },
    { label: 'Moody Yachts', value: 'moodyyachts' },
    { label: 'Moonen Yachts', value: 'moonenyachts' },
    { label: 'Moravia Yachts', value: 'moraviayachts' },
    { label: 'Morgan Yachts', value: 'morganyachts' },
    { label: 'Mosler Yachts', value: 'mosleryachts' },
    { label: 'Mulder Shipyard', value: 'mulder' },
    { label: 'Mulder Yachts', value: 'mulderyachts' },
    { label: 'Multinautic Yachts', value: 'multinauticyachts' },
    { label: 'Mylius Yachts', value: 'myliusyachts' },
    { label: 'Najad Yachts', value: 'najadyachts' },
    { label: 'Naucat Yachts', value: 'naucatsyachts' },
    { label: 'Nauticat Yachts', value: 'nauticatyachts' },
    { label: 'Nautor Swan Yachts', value: 'nautorswanyachts' },
    { label: "Nautor's Swan", value: 'nautorsswan' },
    { label: "Nautor's Swan Yachts", value: 'nautorswanyachts' },
    { label: 'Navigator Yachts', value: 'navigatoryachts' },
    { label: 'Nedship Yachts', value: 'nedshipyachts' },
    { label: 'Neel Trimarans', value: 'neeltrimarans' },
    { label: 'Neptune Yachts', value: 'neptuneyachts' },
    { label: 'Nicholson Yachts', value: 'nichols' },
    { label: 'Nimbus Boats', value: 'nimbusboats' },
    { label: 'Nimbus Yachts', value: 'nimbusyachts' },
    { label: 'NISI Yachts', value: 'nisiyachts' },
    { label: 'Nobiskrug Yachts', value: 'nobiskrugyachts' },
    { label: 'Nordhavn', value: 'nordhavn' },
    { label: 'Nordhavn Yachts', value: 'nordhavn yachts' },
    { label: 'Nordic Tugs', value: 'nordictugs' },
    { label: 'Nordic Yachts', value: 'nordicyachts' },
    { label: 'Nordship Yachts', value: 'nordshipyachts' },
    { label: 'North Wind Yachts', value: 'northwindyachts' },
    { label: 'NorthStar Yachts', value: 'northstaryachts' },
    { label: 'Ocea Yachts', value: 'oceayachts' },
    { label: 'Ocean Alexander', value: 'oceanalexander' },
    { label: 'Ocean Alexander Yachts', value: 'oceanalexanderyachts' },
    { label: 'Ocean Star Yachts', value: 'oceanstaryachts' },
    { label: 'Ocean Voyager', value: 'oceanvoyager' },
    { label: 'Ocean Yachts', value: 'oceanyachts' },
    { label: 'Oceanco', value: 'oceanco' },
    { label: 'Oceanco Yachts', value: 'oceancoyachts' },
    { label: 'OceanFast Yachts', value: 'oceanfastyachts' },
    { label: 'Octo Marine Yachts', value: 'octomarineyachts' },
    { label: 'Octopus Yachts', value: 'octopusyachts' },
    { label: 'Offshore Yachts', value: 'offshoreyachts' },
    { label: 'Orkney Boats', value: 'orkneyboats' },
    { label: 'Otam Yachts', value: 'otamyachts' },
    { label: 'Outer Reef Yachts', value: 'outerreefyachts' },
    { label: 'Overmarine Group', value: 'overmarinegroup' },
    { label: 'Overmarine Group Yachts', value: 'overmarinegroupyachts' },
    { label: 'Overseas Yachts', value: 'overseasyachts' },
    { label: 'Oyster Yachts', value: 'oysteryachts' },
    { label: 'Pachoud Yachts', value: 'pachoudyachts' },
    { label: 'Pacific Asian Enterprises', value: 'pacificasianenterprises' },
    { label: 'Pacific Seacraft', value: 'pacificseacraft' },
    { label: 'Palm Beach Motor Yachts', value: 'palmbeachmotoryachts' },
    { label: 'Palmer Johnson Yachts', value: 'palmerjohnsonyachts' },
    { label: 'Palumbo Yachts', value: 'palumboyachts' },
    { label: 'Pama Yachts', value: 'pamayachts' },
    { label: 'Paragon Yachts', value: 'paragonyachts' },
    { label: 'Pascoe International', value: 'pascoeinternational' },
    { label: 'Pascoe Yachts', value: 'pascoeyachts' },
    { label: 'Patagonia Yachts', value: 'patagoniayachts' },
    { label: 'Pelin Yachts', value: 'pelinyachts' },
    { label: 'Perini Navi Yachts', value: 'perininavi yachts' },
    { label: 'Pershing Yachts', value: 'pershingyachts' },
    { label: 'Picchiotti Yachts', value: 'picchiottiyachts' },
    { label: 'Pine Harbour Yachts', value: 'pineharbouryachts' },
    { label: 'Pirelli Boats', value: 'pirelliboots' },
    { label: 'Pirelli Yachts', value: 'pirelliyachts' },
    { label: 'Pride Mega Yachts', value: 'pridemegayachts' },
    { label: 'Princess Yachts', value: 'princessyachts' },
    { label: 'Privilege Marine', value: 'privilegemarine' },
    { label: 'Privilège Marine Yachts', value: 'privilegemarineyachts' },
    { label: 'Privilege Yachts', value: 'privilegeyachts' },
    { label: 'Privilège Yachts', value: 'privilegeyachts' },
    { label: 'Proteksan Turquoise Yachts', value: 'proteksanturquoiseyachts' },
    { label: 'Pursuit Yachts', value: 'pursuityachts' },
    { label: 'Queen Long Yachts', value: 'queenlongyachts' },
    { label: 'Quicksilver Yachts', value: 'quicksilveryachts' },
    { label: 'Rapsody Yachts', value: 'rapsodyyachts' },
    { label: 'Rayglass Yachts', value: 'rayglassyachts' },
    { label: 'Raymarine Yachts', value: 'raymarineyachts' },
    { label: 'Regal Boats', value: 'regalboats' },
    { label: 'Regulator Marine', value: 'regulatormarine' },
    { label: 'Reichel/Pugh', value: 'reichelpugh' },
    { label: 'Reliant Yachts', value: 'reliantyachts' },
    { label: 'Reverie Yachts', value: 'reverieyachts' },
    { label: 'Rhodes Yachts', value: 'rhodesyachts' },
    { label: 'Richmond Yachts', value: 'richmondyachts' },
    { label: 'Riva Yachts', value: 'rivayachts' },
    { label: 'River Yachts', value: 'riveryachts' },
    { label: 'Riviera Australia', value: 'rivieraaustralia' },
    { label: 'Riviera Yachts', value: 'rivierayachts' },
    { label: 'RM Yachts', value: 'rmyachts' },
    { label: 'Robertson and Caine', value: 'robertsonandcaine' },
    { label: 'Robertson and Caine Yachts', value: 'robertsonandcaineyachts' },
    { label: 'Rodman', value: 'rodman' },
    { label: 'Rodman Yachts', value: 'rodmanyachts' },
    { label: 'Rosen Yachts', value: 'rosenyachts' },
    { label: 'Rossinavi', value: 'rossinavi' },
    { label: 'Rossinavi Yachts', value: 'rossinaviyachts' },
    { label: 'Royal Huisman', value: 'royalhuisman' },
    { label: 'Royal Huisman Yachts', value: 'royalhuismanyachts' },
    { label: 'Rupert Yachts', value: 'rupertyachts' },
    { label: 'SACS Marine', value: 'sacsmarine' },
    { label: 'Saga Yachts', value: 'sagayachts' },
    { label: 'Sailing Yachts', value: 'sailingyachts' },
    { label: 'Saltram Yachts', value: 'saltramyachts' },
    { label: 'San Juan Yachts', value: 'sanjuanyachts' },
    { label: 'Sanlorenzo', value: 'sanlorenzo' },
    { label: 'Sanlorenzo Yachts', value: 'sanlorenzoyachts' },
    { label: 'Santa Cruz Yachts', value: 'santacruzyachts' },
    { label: 'Sargo Yachts', value: 'sargoyachts' },
    { label: 'Sarnico Yachts', value: 'sarnicoyachts' },
    { label: 'Sassicaia Yachts', value: 'sassicaia' },
    { label: 'Saxdor Yachts', value: 'saxdoryachts' },
    { label: 'Sea Ray', value: 'searay' },
    { label: 'Sea Ray Yachts', value: 'searayyachts' },
    { label: 'Sea Yacht', value: 'seayacht' },
    { label: 'Sealine', value: 'sealine' },
    { label: 'Sealine Yachts', value: 'sealineyachts' },
    { label: 'Seaway Yachts', value: 'seawayyachts' },
    { label: 'Seawind Catamarans', value: 'seawindcatamarans' },
    { label: 'Seidelmann Yachts', value: 'seidelmannyachts' },
    { label: 'Serenity Yachts', value: 'serenityyachts' },
    { label: 'Sessa Marine', value: 'sessamarine' },
    { label: 'Sessa Marine Yachts', value: 'sessamarineyachts' },
    { label: 'Shipman Yachts', value: 'shipmanyachts' },
    { label: 'Silverton Marine', value: 'silvertonmarine' },
    { label: 'Silverton Marine Yachts', value: 'silvertonmarineyachts' },
    { label: 'Sinergia Yachts', value: 'sinergiayachts' },
    { label: 'Sirena Yachts', value: 'sirenayachts' },
    { label: 'Skagen Yachts', value: 'skagenyachts' },
    { label: 'Solaris Yachts', value: 'solarisyachts' },
    { label: 'Southerly Yachts', value: 'southerlyyachts' },
    { label: 'Southern Wind', value: 'southernwind' },
    { label: 'Southern Wind Shipyard', value: 'southernwindshipyard' },
    { label: 'Southern Wind Yachts', value: 'southernwindyachts' },
    { label: 'SouthWest Yachts', value: 'southwestyachts' },
    { label: 'Sparkman & Stephens Yachts', value: 'sparkmanstephensyachts' },
    { label: 'Spice Yachts', value: 'spiceyachts' },
    { label: 'Spirithouse Yachts', value: 'spirithouseyachts' },
    { label: 'St. Francis Yachts', value: 'stfrancisyachts' },
    { label: 'Sunreef Yachts', value: 'sunreefyachts' },
    { label: 'Sunseeker', value: 'sunseeker' },
    { label: 'Sunseeker Yachts', value: 'sunseekeryachts' },
    { label: 'Surfer Yachts', value: 'surferyachts' },
    { label: 'Swan Yachts', value: 'swanyachts' },
    { label: 'Swanwick Marina', value: 'swanwickmarina' },
    { label: 'Swanwick Marina Yachts', value: 'swanwickmarinayachts' },
    { label: 'Sweden Yachts', value: 'swedenyachts' },
    { label: 'Swiftships Yachts', value: 'swiftshipsyachts' },
    { label: 'Symbol Yachts', value: 'symbolyachts' },
    { label: 'Symphony Yachts', value: 'symphonyyachts' },
    { label: 'Ta Shing Yachts', value: 'tashingyachts' },
    { label: 'Tansu Yachts', value: 'tansuyachts' },
    { label: 'Targa', value: 'targa' },
    { label: 'Targa Yachts', value: 'targayachts' },
    { label: 'Tarrab Yachts', value: 'tarrabyachts' },
    { label: 'Tartan Yachts', value: 'tartanyachts' },
    { label: 'Tayana Yachts', value: 'tayanayachts' },
    { label: 'Tecnomar', value: 'tecnomar' },
    { label: 'Tecnomar Yachts', value: 'tecnomaryachts' },
    { label: 'Thalassa Yachts', value: 'thalassayachts' },
    { label: 'The Moorings Yachts', value: 'themooringsyachts' },
    { label: 'Thermopylae Clipper Yachts', value: 'thermopylaeclipperyachts' },
    { label: 'Tiara Yachts', value: 'tiarayachts' },
    { label: 'Tige Yachts', value: 'tigeyachts' },
    { label: 'Tigress Yachts', value: 'tigressyachts' },
    { label: 'Time Yachts', value: 'timeyachts' },
    { label: 'Timothy Yachts', value: 'timothyyachts' },
    { label: 'Titan Yachts', value: 'titanyachts' },
    { label: 'Tobago Yachts', value: 'tobagoyachts' },
    { label: 'Tollycraft Yachts', value: 'tollycraftyachts' },
    { label: 'Top Secret Yachts', value: 'topsecretyachts' },
    { label: 'Topaz Yachts', value: 'topazyachts' },
    { label: 'Toscanini Yachts', value: 'toscaniniyachts' },
    { label: 'Townsend Bay Marine', value: 'townsendbaymarine' },
    { label: 'Trader Yachts', value: 'traderyachts' },
    { label: 'Trident Yachts', value: 'tridentyachts' },
    { label: 'Trimarine Yachts', value: 'trimarinesyachts' },
    { label: 'Trintella', value: 'trintella' },
    { label: 'Triton Yachts', value: 'tritonyachts' },
    { label: 'True North Yachts', value: 'truenorthyachts' },
    { label: 'Turquoise Yachts', value: 'turquoiseyachts' },
    { label: 'Twin Disc Yachts', value: 'twindiscyachts' },
    { label: 'Ultimate Yachts', value: 'ultimateyachts' },
    { label: 'Umoe Mandal Yachts', value: 'umoemandalyachts' },
    { label: 'Uniesse Marine Yachts', value: 'uniessemarinyachts' },
    { label: 'Unique Yachts', value: 'uniqueyachts' },
    { label: 'Valencia', value: 'valencia' },
    { label: 'Valiant Yachts', value: 'valiantyachts' },
    { label: 'Valk Yachts', value: 'valkyachts' },
    { label: 'Van de Stadt Design', value: 'vandestadtdesign' },
    { label: 'VanDutch', value: 'vandutch' },
    { label: 'VanDutch Yachts', value: 'vandutchyachts' },
    { label: 'Vanguard Yachts', value: 'vanguardyachts' },
    { label: 'Ventura Yachts', value: 'venturayachts' },
    { label: 'Venture Yachts', value: 'ventureyachts' },
    { label: 'Versilcraft Yachts', value: 'versilcraftyachts' },
    { label: 'Viking Yachts', value: 'vikingyachts' },
    { label: 'Viko Yachts', value: 'vikoyachts' },
    { label: 'Vision Yachts', value: 'visionyachts' },
    { label: 'Vitech Yachts', value: 'vitechyachts' },
    { label: 'Vitters Shipyard', value: 'vittersshipyard' },
    { label: 'Voyage Yachts', value: 'voyageyachts' },
    { label: 'Vripack Yachts', value: 'vripackyachts' },
    { label: 'Wajer Yachts', value: 'wajeryachts' },
    { label: 'Wally Yachts', value: 'wallyyachts' },
    { label: 'Warwick Yachts', value: 'warwickyachts' },
    { label: 'West Bay SonShip Yachts', value: 'westbaysonshipyachts' },
    { label: 'Westerly Yachts', value: 'westerlyyachts' },
    { label: 'Westport Yachts', value: 'westportyachts' },
    { label: 'White Rabbit Yachts', value: 'whiterabbityachts' },
    { label: 'Windy Boats', value: 'windyboats' },
    { label: 'Windy Yachts', value: 'windyyachts' },
    { label: 'Wolf Yachts', value: 'wolfyachts' },
    { label: 'Woodenboat Yachts', value: 'woodenboatyachts' },
    { label: 'Xquisite Yachts', value: 'xquisiteyachts' },
    { label: 'X-Yachts', value: 'xyachts' },
    { label: 'Yachting Developments', value: 'yachtingdevelopments' },
    { label: 'Yachtley', value: 'yachtley' },
    { label: 'Yachtley Yachts', value: 'yachtleyyachts' },
    { label: 'Yachtwerft Yachts', value: 'yachtwerftyachts' },
    { label: 'Yago Yachts', value: 'yagoyachts' },
    { label: 'Zaliv Shipyard', value: 'zalivshipyard' },
    { label: 'Zeelander Yachts', value: 'zeelanderyachts' },
    { label: 'Zodiac Nautic', value: 'zodiacnautic' },
    { label: 'Zodiac Nautic Yachts', value: 'zodiacnauticyachts' },
  ]