export const buggyData =  [
    { label: 'Adder', value: 'adder' },
    { label: 'Advanced EV', value: 'advancedev' },
    { label: 'Adventure Vehicles', value: 'adventurevehicles' },
    { label: 'Aero', value: 'aero' },
    { label: 'American Custom Golf Cars (ACG)', value: 'americancustomgolfcars' },
    { label: 'American Sportworks', value: 'americansportworks' },
    { label: 'Anaconda', value: 'anaconda' },
    { label: 'Arctic Cat', value: 'arcticcat' },
    { label: 'Argo', value: 'argo' },
    { label: 'Argo ATV', value: 'argoatv' },
    { label: 'Asp', value: 'asp' },
    { label: 'AtvMax', value: 'atvmax' },
    { label: 'Bad Boy Buggies', value: 'badboybuggies' },
    { label: 'Baja Dune', value: 'bajadune' },
    { label: 'Baja Motorsports', value: 'bajamotorsports' },
    { label: 'Banshee', value: 'banshee' },
    { label: 'Basilisk', value: 'basilisk' },
    { label: 'Bear Mountain', value: 'bearmountain' },
    { label: 'Beast', value: 'beast' },
    { label: 'Behemoth', value: 'behemoth' },
    { label: 'Big Toys USA', value: 'bigtoysusa' },
    { label: 'Black Mamba', value: 'blackmamba' },
    { label: 'Black Racer', value: 'blackracer' },
    { label: 'Black Snake', value: 'blacksnake' },
    { label: 'Blaze', value: 'blaze' },
    { label: 'Blazer', value: 'blazer' },
    { label: 'Blitz', value: 'blitz' },
    { label: 'BMS Motorsports', value: 'bmsmotorsports' },
    { label: 'Boa', value: 'boa' },
    { label: 'Bobcat', value: 'bobcat' },
    { label: 'Boomslang', value: 'boomslang' },
    { label: 'Brownie', value: 'brownie' },
    { label: 'Buggies Unlimited', value: 'buggiesunlimited' },
    { label: 'Buggy Barn', value: 'buggybarn' },
    { label: 'BuggyWorld', value: 'buggyworld' },
    { label: 'Bush Snake', value: 'bushsnake' },
    { label: 'Bushmaster', value: 'bushmaster' },
    { label: 'Buzzard', value: 'buzzard' },
    { label: 'Can-Am', value: 'canam' },
    { label: 'Carter Brothers', value: 'carterbrothers' },
    { label: 'Cat Snake', value: 'catsnake' },
    { label: 'Centaur', value: 'centaur' },
    { label: 'Cerberus', value: 'cerberus' },
    { label: 'CFMoto', value: 'cfmoto' },
    { label: 'Challenger', value: 'challenger' },
    { label: 'Chimera', value: 'chimera' },
    { label: 'China Golf Carts', value: 'chinagolfcarts' },
    { label: 'Club Car', value: 'clubcar' },
    { label: 'Coachwhip', value: 'coachwhip' },
    { label: 'Cobra', value: 'cobra' },
    { label: 'Colossus', value: 'colossus' },
    { label: 'Comanche', value: 'comanche' },
    { label: 'Condor', value: 'condor' },
    { label: 'Copperhead', value: 'copperhead' },
    { label: 'Coral Snake', value: 'coralsnake' },
    { label: 'Corn Snake', value: 'cornsnake' },
    { label: 'Cottonmouth', value: 'cottonmouth' },
    { label: 'Cougar', value: 'cougar' },
    { label: 'Coyote', value: 'coyote' },
    { label: 'Crossrunner', value: 'crossrunner' },
    { label: 'Cushman', value: 'cushman' },
    { label: 'Cyclops', value: 'cyclops' },
    { label: 'Desert Dingo Racing', value: 'desertdingoracing' },
    { label: 'Desert Fox', value: 'desertfox' },
    { label: 'Desert Snake', value: 'desertsnake' },
    { label: 'Dingo', value: 'dingo' },
    { label: 'Dragon', value: 'dragon' },
    { label: 'Drakart', value: 'drakart' },
    { label: 'Drake', value: 'drake' },
    { label: 'Drive Buggy', value: 'drivebuggy' },
    { label: 'Dune Buggies', value: 'dunebuggies' },
    { label: 'Dwarf', value: 'dwarf' },
    { label: 'Eagle', value: 'eagle' },
    { label: 'Eagle Buggy', value: 'eaglebuggy' },
    { label: 'Ecobuggies', value: 'ecobuggies' },
    { label: 'Electric Cart Company', value: 'electriccartcompany' },
    { label: 'Electric Vehicles International (EVI)', value: 'electricvehiclesinternational' },
    { label: 'Elf', value: 'elf' },
    { label: 'EMC', value: 'emc' },
    { label: 'Evolution Electric Vehicles', value: 'evolutionelectricvehicles' },
    { label: 'Excalibur Golf Cars', value: 'excaliburgolfcars' },
    { label: 'Explorer', value: 'explorer' },
    { label: 'Extreme Buggy', value: 'extremebuggy' },
    { label: 'E-Z-GO', value: 'ezgo' },
    { label: 'Fairplay', value: 'fairplay' },
    { label: 'Fairy', value: 'fairy' },
    { label: 'Falcon', value: 'falcon' },
    { label: 'Ferret', value: 'ferret' },
    { label: 'Flying Snake', value: 'flyingsnake' },
    { label: 'Forest Snake', value: 'forestsnake' },
    { label: 'Fox Racing', value: 'foxracing' },
    { label: 'Freedom Buggies', value: 'freedombuggies' },
    { label: 'Freedom Electric Vehicles', value: 'freedomelectricvehicles' },
    { label: 'Fun Wheels', value: 'funwheels' },
    { label: 'Garia', value: 'garia' },
    { label: 'Garter Snake', value: 'gartersnake' },
    { label: 'Gator', value: 'gator' },
    { label: 'GEM', value: 'gem' },
    { label: 'GEM Car', value: 'gemcar' },
    { label: 'Generic Brand', value: 'genericbrand' },
    { label: 'Giant', value: 'giant' },
    { label: 'Gladiator', value: 'gladiator' },
    { label: 'Goblin', value: 'goblin' },
    { label: 'GoKartsUSA', value: 'gokartsusa' },
    { label: 'Golem', value: 'golem' },
    { label: 'Golf Cart King', value: 'golfcartking' },
    { label: 'Goliath', value: 'goliath' },
    { label: 'Gorgon', value: 'gorgon' },
    { label: 'Grass Snake', value: 'grasssnake' },
    { label: 'Green Snake', value: 'greensnake' },
    { label: 'Gremlin', value: 'gremlin' },
    { label: 'Griffin', value: 'griffin' },
    { label: 'Gryphon', value: 'gryphon' },
    { label: 'Gusto Golf', value: 'gustogolf' },
    { label: 'Hammerhead', value: 'hammerhead' },
    { label: 'Hawk', value: 'hawk' },
    { label: 'HDK Electric Vehicles', value: 'hdkelectricvehicles' },
    { label: 'Hisun', value: 'hisun' },
    { label: 'Hobgoblin', value: 'hobgoblin' },
    { label: 'Honda', value: 'honda' },
    { label: 'Horizon', value: 'horizon' },
    { label: 'Hummer Electric', value: 'hummerelectric' },
    { label: 'Husqvarna', value: 'husqvarna' },
    { label: 'Hydra', value: 'hydra' },
    { label: 'ICON Electric Vehicles', value: 'iconelectricvehicles' },
    { label: 'Imp', value: 'imp' },
    { label: 'Iron Horse', value: 'ironhorse' },
    { label: 'Jackal', value: 'jackal' },
    { label: 'Jaguar', value: 'jaguar' },
    { label: 'Jester', value: 'jester' },
    { label: 'JH Global Services', value: 'jhglobalservices' },
    { label: 'John Deere', value: 'johndeere' },
    { label: 'Joyner', value: 'joyner' },
    { label: 'Jurney', value: 'jurney' },
    { label: 'Kandi', value: 'kandi' },
    { label: 'Kawasaki', value: 'kawasaki' },
    { label: 'Kelpie', value: 'kelpie' },
    { label: 'Kinetic', value: 'kinetic' },
    { label: 'King Cobra', value: 'kingcobra' },
    { label: 'King Snake', value: 'kingsnake' },
    { label: 'Kobold', value: 'kobold' },
    { label: 'Kraken', value: 'kraken' },
    { label: 'Kubota', value: 'kubota' },
    { label: 'Leprechaun', value: 'leprechaun' },
    { label: 'Leviathan', value: 'leviathan' },
    { label: 'Linhai', value: 'linhai' },
    { label: 'Lynx', value: 'lynx' },
    { label: 'MadJax', value: 'madjax' },
    { label: 'Mamba', value: 'mamba' },
    { label: 'Manticore', value: 'manticore' },
    { label: 'Marshell', value: 'marshell' },
    { label: 'Massimo', value: 'massimo' },
    { label: 'Maverick', value: 'maverick' },
    { label: 'Melex', value: 'melex' },
    { label: 'Mermaid', value: 'mermaid' },
    { label: 'Milk Snake', value: 'milksnake' },
    { label: 'Minotaur', value: 'minotaur' },
    { label: 'Mongoose', value: 'mongoose' },
    { label: 'Mountain Snake', value: 'mountainsnake' },
    { label: 'Mud Snake', value: 'mudsnake' },
    { label: 'Mule', value: 'mule' },
    { label: 'Mustang', value: 'mustang' },
    { label: 'Naga', value: 'naga' },
    { label: 'Night Snake', value: 'nightsnake' },
    { label: 'Ocelot', value: 'ocelot' },
    { label: 'Odes', value: 'odes' },
    { label: 'Off-Road Beast', value: 'offroadbeast' },
    { label: 'Ogre', value: 'ogre' },
    { label: 'Orc', value: 'orc' },
    { label: 'Otter', value: 'otter' },
    { label: 'Outfitter Buggies', value: 'outfitterbuggies' },
    { label: 'Outlaw', value: 'outlaw' },
    { label: 'Palm Viper', value: 'palmviper' },
    { label: 'Panther', value: 'panther' },
    { label: 'Paramount Custom Golf Cars', value: 'paramountcustomgolfcars' },
    { label: 'Parcar', value: 'parcar' },
    { label: 'Patriot', value: 'patriot' },
    { label: 'Pegasus', value: 'pegasus' },
    { label: 'Performance Buggy', value: 'performancebuggy' },
    { label: 'Phoenix', value: 'phoenix' },
    { label: 'Pioneer', value: 'pioneer' },
    { label: 'Pit Viper', value: 'pitviper' },
    { label: 'Pixie', value: 'pixie' },
    { label: 'Plain Snake', value: 'plainsnake' },
    { label: 'Platinum EV', value: 'platinumev' },
    { label: 'Polaris', value: 'polaris' },
    { label: 'Pooka', value: 'pooka' },
    { label: 'Power Sports Max', value: 'powersportsmax' },
    { label: 'Predator', value: 'predator' },
    { label: 'Prime Golf Cars', value: 'primegolfcars' },
    { label: 'ProBuggy', value: 'probuggy' },
    { label: 'Puma', value: 'puma' },
    { label: 'Python', value: 'python' },
    { label: 'Racer', value: 'racer' },
    { label: 'Rainbow Snake', value: 'rainbowsnake' },
    { label: 'Rat Snake', value: 'ratsnake' },
    { label: 'Rattler', value: 'rattler' },
    { label: 'Rattlesnake', value: 'rattlesnake' },
    { label: 'Razer', value: 'razer' },
    { label: 'Rebel', value: 'rebel' },
    { label: 'Recoil', value: 'recoil' },
    { label: 'Red Hawk', value: 'redhawk' },
    { label: 'Redcat', value: 'redcat' },
    { label: 'Renegade', value: 'renegade' },
    { label: 'Revolution', value: 'revolution' },
    { label: 'Revolution Golf Cars', value: 'revolutiongolfcars' },
    { label: 'Revolution Off-Road', value: 'revolutionoffroad' },
    { label: 'Ridge Runner', value: 'ridgerunner' },
    { label: 'Ringneck Snake', value: 'ringnecksnake' },
    { label: 'Rock Snake', value: 'rocksnake' },
    { label: 'Roketa', value: 'roketa' },
    { label: 'Rough Rider', value: 'roughrider' },
    { label: 'Royal EV', value: 'royalev' },
    { label: 'Rugged Ridge', value: 'ruggedridge' },
    { label: 'Sabre', value: 'sabre' },
    { label: 'Sand Blaster', value: 'sandblaster' },
    { label: 'Sand Rail', value: 'sandrail' },
    { label: 'Sand Snake', value: 'sandsnake' },
    { label: 'Sandstorm', value: 'sandstorm' },
    { label: 'Scorpion', value: 'scorpion' },
    { label: 'Sea Buggy', value: 'seabuggy' },
    { label: 'Sea Snake', value: 'seasnake' },
    { label: 'Segway', value: 'segway' },
    { label: 'Selkie', value: 'selkie' },
    { label: 'Serpent', value: 'serpent' },
    { label: 'Sidewinder', value: 'sidewinder' },
    { label: 'Smooth Snake', value: 'smoothsnake' },
    { label: 'Snake', value: 'snake' },
    { label: 'Sonic Buggy', value: 'sonicbuggy' },
    { label: 'Speed Buggy', value: 'speedbuggy' },
    { label: 'Speed Racer', value: 'speedracer' },
    { label: 'Sphinx', value: 'sphinx' },
    { label: 'Spider', value: 'spider' },
    { label: 'Sprite', value: 'sprite' },
    { label: 'Star EV', value: 'starev' },
    { label: 'Stealth', value: 'stealth' },
    { label: 'Steel Buggy', value: 'steelbuggy' },
    { label: 'Stingray', value: 'stingray' },
    { label: 'Street Legal Golf Cars', value: 'streetlegalgolfcars' },
    { label: 'Streetrod', value: 'streetrod' },
    { label: 'STX Golf Buggies', value: 'stxgolfbuggies' },
    { label: 'Sun Mountain', value: 'sunmountain' },
    { label: 'Swamp Fox', value: 'swampfox' },
    { label: 'Swamp Snake', value: 'swampsnake' },
    { label: 'Sylph', value: 'sylph' },
    { label: 'Talon', value: 'talon' },
    { label: 'Thunder', value: 'thunder' },
    { label: 'Tiger', value: 'tiger' },
    { label: 'Titan', value: 'titan' },
    { label: 'Titan Golf Cars', value: 'titangolfcars' },
    { label: 'Tomberlin', value: 'tomberlin' },
    { label: 'Tornado', value: 'tornado' },
    { label: 'Trail Hawk', value: 'trailhawk' },
    { label: 'TrailBlazer', value: 'trailblazer' },
    { label: 'Trailcat', value: 'trailcat' },
    { label: 'TrailMaster', value: 'trailmaster' },
    { label: 'Tree Snake', value: 'treesnake' },
    { label: 'Triton', value: 'triton' },
    { label: 'Trojan Golf Cars', value: 'trojangolfcars' },
    { label: 'Troll', value: 'troll' },
    { label: 'Ultra4', value: 'ultra4' },
    { label: 'Victory', value: 'victory' },
    { label: 'Vine Snake', value: 'vinesnake' },
    { label: 'Viper', value: 'viper' },
    { label: 'Volition', value: 'volition' },
    { label: 'Vulture', value: 'vulture' },
    { label: 'Warrior', value: 'warrior' },
    { label: 'Water Moccasin', value: 'watermoccasin' },
    { label: 'Water Snake', value: 'watersnake' },
    { label: 'Wildcat', value: 'wildcat' },
    { label: 'Wolverine', value: 'wolverine' },
    { label: 'Wyrm', value: 'wyrm' },
    { label: 'Wyvern', value: 'wyvern' },
    { label: 'Xinyang', value: 'xinyang' },
    { label: 'Xtreme Buggies', value: 'xtremebuggies' },
    { label: 'Yamaha', value: 'yamaha' },
    { label: 'Yamaha Golf Car', value: 'yamahagolfcar' }
]