export const busesData = [
    { label: 'Alexander Dennis', value: 'alexanderdennis' },
    { label: 'Anhui Hualing', value: 'anhhuihualing' },
    { label: 'Ankai', value: 'ankai' },
    { label: 'Ankai Automobile', value: 'ankaiautomobile' },
    { label: 'Ashok Leyland', value: 'ashokleyland' },
    { label: 'Autosan', value: 'autosan' },
    { label: 'BAIC', value: 'baic' },
    { label: 'Baoding Dadi', value: 'baodingdadi' },
    { label: 'Beijing Bus', value: 'beijingbus' },
    { label: 'Beijing Heavy Duty Truck', value: 'beijingheavydutytruck' },
    { label: 'Beijing Hualin', value: 'beijinghualin' },
    { label: 'Beiqi Foton', value: 'beiqifoton' },
    { label: 'Belarusian Automobile Plant', value: 'belarusianautomobileplant' },
    { label: 'Blue Bird', value: 'bluebird' },
    { label: 'BYD', value: 'byd' },
    { label: 'Caio', value: 'caio' },
    { label: 'Carrus', value: 'carrus' },
    { label: 'Chang’an', value: 'changan' },
    { label: 'Changan', value: 'changan' },
    { label: 'Changan Auto', value: 'changanauto' },
    { label: 'Changjiang', value: 'changjiang' },
    { label: 'Chery', value: 'chery' },
    { label: 'Chery Commercial', value: 'cherycommercial' },
    { label: 'Chevrolet', value: 'chevrolet' },
    { label: 'China Bus', value: 'chinabus' },
    { label: 'Chongqing Qingling', value: 'chongqingqingling' },
    { label: 'Citroën', value: 'citroen' },
    { label: 'Daewoo', value: 'daewoo' },
    { label: 'DAF', value: 'daf' },
    { label: 'Dandong Bus', value: 'dandongbus' },
    { label: 'Dandong Huanghai', value: 'dandonghuanghai' },
    { label: 'Dennis Eagle', value: 'denniseagle' },
    { label: 'Dongfeng', value: 'dongfeng' },
    { label: 'Dongfeng Cummins', value: 'dongfengcummins' },
    { label: 'Dongfeng Motor', value: 'dongfengmotor' },
    { label: 'Dongfeng Motor Corporation', value: 'dongfengmotorcorporation' },
    { label: 'Dongfeng Sokon', value: 'dongfengsokon' },
    { label: 'Eicher', value: 'eicher' },
    { label: 'FAMSA', value: 'famsa' },
    { label: 'FAW', value: 'faw' },
    { label: 'FAW Bus and Coach', value: 'fawbusandcoach' },
    { label: 'FAW Haima', value: 'fawhaima' },
    { label: 'FAW Jiefang', value: 'fawjiefang' },
    { label: 'Fiat', value: 'fiat' },
    { label: 'Force Motors', value: 'forcemotors' },
    { label: 'Ford', value: 'ford' },
    { label: 'Foton', value: 'foton' },
    { label: 'Foton AUV', value: 'fotona' },
    { label: 'Freightliner', value: 'freightliner' },
    { label: 'Fujian Benz', value: 'fujianbenz' },
    { label: 'GAC Group', value: 'gacgroup' },
    { label: 'GAC Trumpchi', value: 'gactrumpchi' },
    { label: 'GAZ', value: 'gaz' },
    { label: 'Geely', value: 'geely' },
    { label: 'Gillig', value: 'gillig' },
    { label: 'GMC', value: 'gmc' },
    { label: 'Golden Dragon', value: 'goldendragon' },
    { label: 'Great Dragon', value: 'greatdragon' },
    { label: 'Great Wall', value: 'greatwall' },
    { label: 'Great Wall Motors', value: 'greatwallmotors' },
    { label: 'Gree', value: 'gree' },
    { label: 'Gree Electric', value: 'greeelectric' },
    { label: 'Greeves', value: 'greeves' },
    { label: 'Guangxi Yuchai', value: 'guangxiyuchai' },
    { label: 'Guangzhou Yangcheng', value: 'guangzhouyangcheng' },
    { label: 'Guilin Daewoo', value: 'guilindaewoo' },
    { label: 'Hafei', value: 'hafei' },
    { label: 'Haima', value: 'haima' },
    { label: 'Harbin Hafei', value: 'harbinhafei' },
    { label: 'Hebei Chang\'an', value: 'hebeichangan' },
    { label: 'Hebei Yutong', value: 'hebeiyutong' },
    { label: 'Henan Xinfei', value: 'henanxinfei' },
    { label: 'Higer', value: 'higer' },
    { label: 'Hino', value: 'hino' },
    { label: 'Hongqi', value: 'hongqi' },
    { label: 'Hualing', value: 'hualing' },
    { label: 'Hualong', value: 'hualong' },
    { label: 'Hunan Bus', value: 'hunanbus' },
    { label: 'Hunan CSR Times', value: 'hunancsrtimes' },
    { label: 'Hyundai', value: 'hyundai' },
    { label: 'IC Bus', value: 'icbus' },
    { label: 'Irizar', value: 'irizar' },
    { label: 'Isuzu', value: 'isuzu' },
    { label: 'Iveco', value: 'iveco' },
    { label: 'Iveco Magirus', value: 'ivecomagirus' },
    { label: 'JAC', value: 'jac' },
    { label: 'JAC Motors', value: 'jacmotors' },
    { label: 'Jelcz', value: 'jelcz' },
    { label: 'Jianghuai', value: 'jianghuai' },
    { label: 'Jiangling Motors', value: 'jianglingmotors' },
    { label: 'Jiangsu Kawei', value: 'jiangsukawei' },
    { label: 'Jiangxi Kama', value: 'jiangxikama' },
    { label: 'Jinbei', value: 'jinbei' },
    { label: 'Jinghua', value: 'jinghua' },
    { label: 'Jinma', value: 'jinma' },
    { label: 'JMC', value: 'jmc' },
    { label: 'Karosa', value: 'karosa' },
    { label: 'Karsan', value: 'karsan' },
    { label: 'Kia', value: 'kia' },
    { label: 'King Long', value: 'kinglong' },
    { label: 'King Long United Automotive', value: 'kinglongunitedautomotive' },
    { label: 'KrAZ', value: 'kraz' },
    { label: 'Kuban', value: 'kuban' },
    { label: 'LAZ', value: 'laz' },
    { label: 'Lifan', value: 'lifan' },
    { label: 'Mahindra', value: 'mahindra' },
    { label: 'MAN', value: 'man' },
    { label: 'Marcopolo', value: 'marcopolo' },
    { label: 'MAZ', value: 'maz' },
    { label: 'Mazda', value: 'mazda' },
    { label: 'Mercedes-Benz', value: 'mercedesbenz' },
    { label: 'Mitsubishi Fuso', value: 'mitsubishifuso' },
    { label: 'Motor Coach Industries (MCI)', value: 'motorcoachindustries' },
    { label: 'Mudan', value: 'mudan' },
    { label: 'Nanjing Automobile', value: 'nanjingautomobile' },
    { label: 'Naveco', value: 'naveco' },
    { label: 'Neoplan', value: 'neoplan' },
    { label: 'New Flyer', value: 'newflyer' },
    { label: 'Nissan', value: 'nissan' },
    { label: 'Optare', value: 'optare' },
    { label: 'Otokar', value: 'otokar' },
    { label: 'PAZ', value: 'paz' },
    { label: 'Peugeot', value: 'peugeot' },
    { label: 'Plaxton', value: 'plaxton' },
    { label: 'Prevost', value: 'prevost' },
    { label: 'Qinchuan', value: 'qinchuan' },
    { label: 'Qingdao Haier', value: 'qingdaohaier' },
    { label: 'Qingling', value: 'qingling' },
    { label: 'Ram', value: 'ram' },
    { label: 'Renault', value: 'renault' },
    { label: 'Robur', value: 'robur' },
    { label: 'Rocar', value: 'rocar' },
    { label: 'SAIC Motor', value: 'saicmotor' },
    { label: 'Sanos', value: 'sanos' },
    { label: 'Scania', value: 'scania' },
    { label: 'Scania-Vabis', value: 'scaniavabis' },
    { label: 'Setra', value: 'setra' },
    { label: 'Shaanxi Auto', value: 'shaanxiauto' },
    { label: 'Shaanxi Automobile', value: 'shaanxiautomobile' },
    { label: 'Shandong KAMA', value: 'shandongkama' },
    { label: 'Shandong Taikai', value: 'shandongtaikai' },
    { label: 'Shanghai Shenlong', value: 'shanghaishenlong' },
    { label: 'Shaolin Bus', value: 'shaolinbus' },
    { label: 'Shenlong', value: 'shenlong' },
    { label: 'Shenyang Jinbei', value: 'shenyangjinbei' },
    { label: 'Shenzhen Wuzhoulong', value: 'shenzhenwuzhoulong' },
    { label: 'Sileo', value: 'sileo' },
    { label: 'Sisu', value: 'sisu' },
    { label: 'Skoda', value: 'skoda' },
    { label: 'Solaris', value: 'solaris' },
    { label: 'Star', value: 'star' },
    { label: 'Sunlong', value: 'sunlong' },
    { label: 'Suzhou Higer', value: 'suzhouhiger' },
    { label: 'TAM', value: 'tam' },
    { label: 'Tata Motors', value: 'tatamotors' },
    { label: 'Temsa', value: 'temsa' },
    { label: 'Thomas Built Buses', value: 'thomasbuiltbuses' },
    { label: 'Tianjin Binhai', value: 'tianjinbinhai' },
    { label: 'Tianjin FAW', value: 'tianjinfaw' },
    { label: 'Toyota', value: 'toyota' },
    { label: 'UAZ', value: 'uaz' },
    { label: 'Van Hool', value: 'vanhool' },
    { label: 'VDL', value: 'vdl' },
    { label: 'VDL Berkhof', value: 'vdlberkhof' },
    { label: 'Vest', value: 'vest' },
    { label: 'Volgren', value: 'volgren' },
    { label: 'Volkswagen', value: 'volkswagen' },
    { label: 'Volvo', value: 'volvo' },
    { label: 'Weichai', value: 'weichai' },
    { label: 'Weichai Power', value: 'weichaipower' },
    { label: 'Wrightbus', value: 'wrightbus' },
    { label: 'Wuzhoulong', value: 'wuzhoulong' },
    { label: 'XCMG', value: 'xcmg' },
    { label: 'Xiamen Auto', value: 'xiamenauto' },
    { label: 'Xiamen Golden Dragon', value: 'xiamengoldendragon' },
    { label: 'Xiamen King Long', value: 'xiamenkinglong' },
    { label: 'Xiangtan Electric', value: 'xiangtanelectric' },
    { label: 'Yaxing', value: 'yaxing' },
    { label: 'Yinlong', value: 'yinlong' },
    { label: 'Youngman', value: 'youngman' },
    { label: 'YTO', value: 'yto' },
    { label: 'Yuchai', value: 'yuchai' },
    { label: 'Yutong', value: 'yutong' },
    { label: 'Zhengzhou Nissan', value: 'zhengzhounissan' },
    { label: 'Zhengzhou Yutong', value: 'zhengzhouyutong' },
    { label: 'Zhongtong', value: 'zhongtong' },
    { label: 'Zhongwei', value: 'zhongwei' },
    { label: 'Zhongxing', value: 'zhongxing' },
    { label: 'Zhongxing Automobile', value: 'zhongxingautomobile' },
    { label: 'Zhongyuan', value: 'zhongyuan' }
]