export const carsData = [
    { label: 'Acura', value: 'acura' },
    { label: 'Alfa Romeo', value: 'alfaromeo' },
    { label: 'Aptera Motors', value: 'apteramotors' },
    { label: 'Arcfox', value: 'arcfox' },
    { label: 'Ariel Motor Company', value: 'arielmotorcompany' },
    { label: 'Ascari Cars', value: 'ascaricars' },
    { label: 'Aspark', value: 'aspark' },
    { label: 'Aston Martin', value: 'astonmartin' },
    { label: 'Audi', value: 'audi' },
    { label: 'Automobili Pininfarina', value: 'automobilipininfarina' },
    { label: 'Baojun', value: 'baojun' },
    { label: 'Bentley', value: 'bentley' },
    { label: 'BMW', value: 'bmw' },
    { label: 'Bollinger Motors', value: 'bollingermotors' },
    { label: 'Brilliance Auto', value: 'brillianceauto' },
    { label: 'Bugatti', value: 'bugatti' },
    { label: 'Buick', value: 'buick' },
    { label: 'BYD', value: 'byd' },
    { label: 'Byton', value: 'byton' },
    { label: 'Cadillac', value: 'cadillac' },
    { label: 'Canoo', value: 'canoo' },
    { label: 'Caterham Cars', value: 'caterhamcars' },
    { label: 'Changan Automobile', value: 'changanautomobile' },
    { label: 'Changhe', value: 'changhe' },
    { label: 'Chery', value: 'chery' },
    { label: 'Chevrolet', value: 'chevrolet' },
    { label: 'Chrysler', value: 'chrysler' },
    { label: 'Citroën', value: 'citroen' },
    { label: 'Cowin Auto', value: 'cowinauto' },
    { label: 'Dacia', value: 'dacia' },
    { label: 'Daihatsu', value: 'daihatsu' },
    { label: 'Datsun', value: 'datsun' },
    { label: 'Dodge', value: 'dodge' },
    { label: 'Dongfeng Motor', value: 'dongfengmotor' },
    { label: 'Donkervoort', value: 'donkervoort' },
    { label: 'Drako Motors', value: 'drakomotors' },
    { label: 'DS Automobiles', value: 'dsautomobiles' },
    { label: 'Eagle', value: 'eagle' },
    { label: 'Everus', value: 'everus' },
    { label: 'Exagon Motors', value: 'exagonmotors' },
    { label: 'Faraday Future', value: 'faradayfuture' },
    { label: 'FAW Group', value: 'fawgroup' },
    { label: 'Ferrari', value: 'ferrari' },
    { label: 'Fiat', value: 'fiat' },
    { label: 'Fisker', value: 'fisker' },
    { label: 'Fisker Inc.', value: 'fiskerinc' },
    { label: 'Ford', value: 'ford' },
    { label: 'Foton', value: 'foton' },
    { label: 'GAC Motor', value: 'gacmotor' },
    { label: 'Geely', value: 'geely' },
    { label: 'Genesis', value: 'genesis' },
    { label: 'Genovation Cars', value: 'genovationcars' },
    { label: 'Ginetta', value: 'ginetta' },
    { label: 'GMC', value: 'gmc' },
    { label: 'Great Wall Motors', value: 'greatwallmotors' },
    { label: 'Haima', value: 'haima' },
    { label: 'Hanteng', value: 'hanteng' },
    { label: 'Haval', value: 'haval' },
    { label: 'Hawtai', value: 'hawtai' },
    { label: 'Hino', value: 'hino' },
    { label: 'Hispano Suiza', value: 'hispanosuiza' },
    { label: 'Holden', value: 'holden' },
    { label: 'Honda', value: 'honda' },
    { label: 'Hongqi', value: 'hongqi' },
    { label: 'Hyundai', value: 'hyundai' },
    { label: 'Infiniti', value: 'infiniti' },
    { label: 'Iveco', value: 'iveco' },
    { label: 'JAC Motors', value: 'jacmotors' },
    { label: 'Jaguar', value: 'jaguar' },
    { label: 'Jeep', value: 'jeep' },
    { label: 'Jiangling Motors', value: 'jianglingmotors' },
    { label: 'JMC', value: 'jmc' },
    { label: 'Karma Automotive', value: 'karmaautomotive' },
    { label: 'Karry', value: 'karry' },
    { label: 'Kia', value: 'kia' },
    { label: 'Koenigsegg', value: 'koenigsegg' },
    { label: 'Lada', value: 'lada' },
    { label: 'Lancia', value: 'lancia' },
    { label: 'Land Rover', value: 'landrover' },
    { label: 'Leopaard', value: 'leopaard' },
    { label: 'Lexus', value: 'lexus' },
    { label: 'Li Auto', value: 'liauto' },
    { label: 'Lightyear', value: 'lightyear' },
    { label: 'Lincoln', value: 'lincoln' },
    { label: 'Lordstown Motors', value: 'lordstownmotors' },
    { label: 'Lotus', value: 'lotus' },
    { label: 'Lucid Motors', value: 'lucidmotors' },
    { label: 'Luxgen', value: 'luxgen' },
    { label: 'Lynk & Co', value: 'lynkco' },
    { label: 'Mahindra', value: 'mahindra' },
    { label: 'Maserati', value: 'maserati' },
    { label: 'Mazda', value: 'mazda' },
    { label: 'McLaren', value: 'mclaren' },
    { label: 'Mercedes-Benz', value: 'mercedesbenz' },
    { label: 'MG Motor', value: 'mgmotor' },
    { label: 'Mini', value: 'mini' },
    { label: 'Mitsubishi', value: 'mitsubishi' },
    { label: 'Mullen Technologies', value: 'mullentechnologies' },
    { label: 'Nikola Motor Company', value: 'nikolamotorcompany' },
    { label: 'Nio', value: 'nio' },
    { label: 'Nissan', value: 'nissan' },
    { label: 'Noble Automotive', value: 'nobleautomotive' },
    { label: 'Opel', value: 'opel' },
    { label: 'Pagani', value: 'pagani' },
    { label: 'Perodua', value: 'perodua' },
    { label: 'Peugeot', value: 'peugeot' },
    { label: 'Pininfarina', value: 'pininfarina' },
    { label: 'Polestar', value: 'polestar' },
    { label: 'Porsche', value: 'porsche' },
    { label: 'Proton', value: 'proton' },
    { label: 'Qoros', value: 'qoros' },
    { label: 'Radical Sportscars', value: 'radicalsportscars' },
    { label: 'RAM', value: 'ram' },
    { label: 'Renault', value: 'renault' },
    { label: 'Rimac Automobili', value: 'rimacautomobili' },
    { label: 'Rivian', value: 'rivian' },
    { label: 'Roewe', value: 'roewe' },
    { label: 'Rolls-Royce', value: 'rollsroyce' },
    { label: 'Rover', value: 'rover' },
    { label: 'Saab', value: 'saab' },
    { label: 'Saturn', value: 'saturn' },
    { label: 'Scion', value: 'scion' },
    { label: 'SEAT', value: 'seat' },
    { label: 'Seres', value: 'seres' },
    { label: 'Shelby', value: 'shelby' },
    { label: 'Skoda', value: 'skoda' },
    { label: 'Smart', value: 'smart' },
    { label: 'Sono Motors', value: 'sonomotors' },
    { label: 'Soueast', value: 'soueast' },
    { label: 'Spyker', value: 'spyker' },
    { label: 'SsangYong', value: 'ssangyong' },
    { label: 'SSC North America', value: 'sscnorthamerica' },
    { label: 'Subaru', value: 'subaru' },
    { label: 'Suzuki', value: 'suzuki' },
    { label: 'Tata Motors', value: 'tatamotors' },
    { label: 'Techrules', value: 'techrules' },
    { label: 'Tesla', value: 'tesla' },
    { label: 'Thunder Power', value: 'thunderpower' },
    { label: 'Toyota', value: 'toyota' },
    { label: 'UAZ', value: 'uaz' },
    { label: 'Vauxhall', value: 'vauxhall' },
    { label: 'Volkswagen', value: 'volkswagen' },
    { label: 'Volvo', value: 'volvo' },
    { label: 'WEY', value: 'wey' },
    { label: 'Wiesmann', value: 'wiesmann' },
    { label: 'WM Motor', value: 'wmmotor' },
    { label: 'Wuling', value: 'wuling' },
    { label: 'Xpeng Motors', value: 'xpengmotors' },
    { label: 'Zenvo Automotive', value: 'zenvoautomotive' },
    { label: 'Zotye', value: 'zotye' },
  ]