export const chartersData = [
    { label: 'Adam Aircraft Industries', value: 'adamaircraftindustries' },
    {
      label: 'Advanced Composite Structures',
      value: 'advancedcompositestructures',
    },
    { label: 'Aero Adventure Aviation', value: 'aeroadventureaviation' },
    { label: 'Aero Vodochody', value: 'aerovodochody' },
    { label: 'AeroEast Europe', value: 'aeroeasteurope' },
    { label: 'Aeroprakt', value: 'aeroprakt' },
    { label: 'Aerospool', value: 'aerospool' },
    { label: 'Aerostar Aircraft', value: 'aerostaraircraft' },
    { label: 'Aerotechnik', value: 'aerotechnik' },
    { label: 'AgustaWestland', value: 'agustawestland' },
    { label: 'Air Tractor', value: 'airtractor' },
    { label: 'Airbus Helicopters', value: 'airbushelicopters' },
    { label: 'AirCam', value: 'aircam' },
    { label: 'Alpi Aviation', value: 'alpiaviation' },
    { label: 'American Champion Aircraft', value: 'americanchampionaircraft' },
    { label: 'Antonov', value: 'antonov' },
    { label: 'Atec Aircraft', value: 'atecaircraft' },
    { label: 'AutoGyro', value: 'autogyro' },
    { label: 'Avanti Aviation', value: 'avantiaviation' },
    { label: 'Aviat Aircraft', value: 'aviataircraft' },
    { label: 'AVIC Helicopter Company', value: 'avichelicoptercompany' },
    { label: 'Bearhawk', value: 'bearhawk' },
    { label: 'Bearhawk Aircraft', value: 'bearhawkaircraft' },
    { label: 'Beechcraft', value: 'beechcraft' },
    { label: 'Beechcraft King Air', value: 'beechcraftkingair' },
    { label: 'Bell Boeing', value: 'bellboeing' },
    { label: 'Bell Helicopter', value: 'bellhelicopter' },
    { label: 'Bell V-22 Osprey', value: 'bellv22osprey' },
    { label: 'Blackshape Aircraft', value: 'blackshapaircraft' },
    { label: 'Boeing Rotorcraft Systems', value: 'boeingrotorcraftsystems' },
    { label: 'Bombardier', value: 'bombardier' },
    { label: 'Brantly International', value: 'brantlyinternational' },
    { label: 'Bristell Aircraft', value: 'bristellaircraft' },
    { label: 'Britten-Norman', value: 'brittennorman' },
    { label: 'BRM Aero', value: 'brmaero' },
    { label: 'Calidus Aircraft', value: 'calidusaircraft' },
    { label: 'Cessna', value: 'cessna' },
    { label: 'Cessna 172', value: 'cessna172' },
    { label: 'Cessna 182', value: 'cessna182' },
    { label: 'Cessna 206', value: 'cessna206' },
    {
      label: 'Changhe Aircraft Industries',
      value: 'changheaircraftindustries',
    },
    { label: 'Cirrus Aircraft', value: 'cirrusaircraft' },
    { label: 'Corvus Aircraft', value: 'corvusaircraft' },
    { label: 'CubCrafters', value: 'cubcrafters' },
    { label: 'Czech Sport Aircraft', value: 'czechsportaircraft' },
    { label: 'Daher', value: 'daher' },
    { label: 'Dassault Aviation', value: 'dassaultaviation' },
    { label: 'Denel Aviation', value: 'denelaviation' },
    { label: 'Diamond Aircraft', value: 'diamondaircraft' },
    { label: 'Diamond DA40', value: 'diamondda40' },
    { label: 'Diamond DA42', value: 'diamondda42' },
    { label: 'Diamond DA42 Twin Star', value: 'diamondda42twinstar' },
    { label: 'Diamond DA62', value: 'diamondda62' },
    { label: 'Diamond Twin Star', value: 'diamondtwinstar' },
    { label: "Dyn'Aéro", value: 'dynaero' },
    { label: 'Dynali Helicopter Company', value: 'dynalihelicoptercompany' },
    { label: 'Eclipse Aerospace', value: 'eclipseaerospace' },
    { label: 'EHang', value: 'ehang' },
    { label: 'Embraer', value: 'embraer' },
    {
      label: 'Enstrom Helicopter Corporation',
      value: 'enstromhelicoptercorporation',
    },
    { label: 'Epic Aircraft', value: 'epicaircraft' },
    { label: 'Eurocopter', value: 'eurocopter' },
    { label: 'Evektor-Aerotechnik', value: 'evektoraerotechnik' },
    { label: 'Extra Aircraft', value: 'extraaircraft' },
    { label: 'Extra EA-300', value: 'extraea300' },
    { label: 'Extra EA-500', value: 'extraea500' },
    { label: 'Extra Flugzeugbau', value: 'extraflugzeugbau' },
    {
      label: 'Fabrica Argentina de Aviones',
      value: 'fabricaargentinadeaviones',
    },
    { label: 'Fisher Flying Products', value: 'fisherflyingproducts' },
    { label: 'Flight Design', value: 'flightdesign' },
    { label: 'Flight Design CTLS', value: 'flightdesignctls' },
    { label: 'Fly Synthesis', value: 'flysynthesis' },
    { label: 'Flylab Aircraft', value: 'flylabaircraft' },
    { label: 'GippsAero', value: 'gippsaero' },
    { label: 'Glasair Aviation', value: 'glasairaviation' },
    { label: 'Glasair Sportsman', value: 'glasairsportsman' },
    { label: 'Great Lakes Aircraft', value: 'greatlakesaircraft' },
    { label: 'Grob Aircraft', value: 'grobaircraft' },
    { label: 'Groppo Aviation', value: 'groppoaviation' },
    { label: 'Gulfstream Aerospace', value: 'gulfstreamaerospace' },
    { label: 'Gulfstream G280', value: 'gulfstreamg280' },
    { label: 'Gulfstream G450', value: 'gulfstreamg450' },
    { label: 'Hawker Beechcraft', value: 'hawkerbeechcraft' },
    { label: 'Helibras', value: 'helibras' },
    {
      label: 'Hindustan Aeronautics Limited',
      value: 'hindustanaeronauticslimited',
    },
    { label: 'Honda Aircraft Company', value: 'hondaircraftcompany' },
    { label: 'HondaJet', value: 'hondajet' },
    { label: 'Hughes Helicopters', value: 'hugheshelicopters' },
    { label: 'Icon A5', value: 'icona5' },
    { label: 'ICON Aircraft', value: 'iconaircraft' },
    { label: 'ICP Srl', value: 'icpsrl' },
    { label: 'Jihlavan Aircraft', value: 'jihlavanaircraft' },
    { label: 'JMB Aircraft', value: 'jmbaircraft' },
    { label: 'Just Aircraft', value: 'justaircraft' },
    { label: 'Kaman Aircraft', value: 'kamanaircraft' },
    { label: 'Kamov', value: 'kamov' },
    { label: 'Kawasaki Heavy Industries', value: 'kawasakiheavyindustries' },
    { label: 'Kazan Helicopters', value: 'kazanhelicopters' },
    { label: 'King Air 350i', value: 'kingair350i' },
    { label: 'Kitfox Aircraft', value: 'kitfoxaircraft' },
    { label: 'Kodiak Aircraft Company', value: 'kodiakaircraftcompany' },
    { label: 'Korea Aerospace Industries', value: 'koreaaerospaceindustries' },
    { label: 'Lake Aircraft', value: 'lakeaircraft' },
    { label: 'Lancair Evolution', value: 'lancairevolution' },
    { label: 'Lancair International', value: 'lancairinternational' },
    { label: 'Leonardo Helicopters', value: 'leonardohelicopters' },
    { label: 'Magni Gyro', value: 'magnigyro' },
    { label: 'Mahindra Aerospace', value: 'mahindraaerospace' },
    { label: 'Maule Air', value: 'mauleair' },
    { label: 'Maule Aircraft', value: 'mauleaircraft' },
    { label: 'MD Helicopters', value: 'mdhelicopters' },
    { label: 'Mil Helicopters', value: 'milhelicopters' },
    {
      label: 'Mooney International Corporation',
      value: 'mooneyinternationalcorporation',
    },
    { label: 'Mooney M20', value: 'mooneym20' },
    { label: 'Murphy Aircraft', value: 'murphyaircraft' },
    { label: 'NHIndustries', value: 'nhindustries' },
    { label: 'North American Rockwell', value: 'northamericanrockwell' },
    { label: 'Northrop Grumman', value: 'northropgrumman' },
    { label: 'Pacific Aerospace', value: 'pacificaerospace' },
    { label: 'Piaggio Aerospace', value: 'piaggioaerospace' },
    { label: 'Pilatus Aircraft', value: 'pilatusaircraft' },
    { label: 'Pilatus PC-12', value: 'pilatuspc12' },
    { label: 'Piper Aircraft', value: 'piperaicraft' },
    { label: 'Piper M600', value: 'piperm600' },
    { label: 'Piper PA-28 Cherokee', value: 'piperpa28cherokee' },
    { label: 'Piper PA-46', value: 'piperpa46' },
    { label: 'Pipistrel', value: 'pipistrel' },
    { label: 'Progressive Aerodyne', value: 'progressiveaerodyne' },
    { label: 'PZL Mielec', value: 'pzl mielec' },
    { label: 'PZL-Świdnik', value: 'pzlswidnik' },
    { label: 'Quest Aircraft Company', value: 'questaircraftcompany' },
    { label: 'Quest Kodiak 100', value: 'questkodiak100' },
    { label: 'Quicksilver Aircraft', value: 'quicksilveraircraft' },
    { label: 'Rans Designs', value: 'ransdesigns' },
    { label: 'Robin Aircraft', value: 'robinaircraft' },
    {
      label: 'Robinson Helicopter Company',
      value: 'robinsonhelicoptercompany',
    },
    { label: 'Rockwell Collins', value: 'rockwellcollins' },
    { label: 'Russian Helicopters', value: 'russianhelicopters' },
    { label: 'Seamax Aircraft', value: 'seamaxaircraft' },
    { label: 'Shark Aero', value: 'sharkaero' },
    { label: 'Sikorsky Aircraft', value: 'sikorskyaircraft' },
    { label: 'Sikorsky HH-60 Pave Hawk', value: 'sikorskyhh60pavehawk' },
    { label: 'SkyCraft Airplanes', value: 'skycraftairplanes' },
    { label: 'SkyReach Aircraft', value: 'skyreachaircraft' },
    { label: 'Socata', value: 'socata' },
    { label: 'Socata TBM 900', value: 'socatatbm900' },
    { label: 'Sonex Aircraft', value: 'sonexaircraft' },
    { label: 'Tecnam', value: 'tecnam' },
    { label: 'Tecnam P2012 Traveller', value: 'tecnap2012traveller' },
    { label: 'Textron Aviation', value: 'textronaviation' },
    { label: 'TL Ultralight', value: 'tlultralight' },
    { label: 'UTVA Aviation Industry', value: 'utvaaviationindustry' },
    { label: "Van's Aircraft", value: 'vansaircraft' },
    { label: 'Velocity Aircraft', value: 'velocityaircraft' },
    { label: 'Viking Air', value: 'vikingair' },
    { label: 'Viper Aircraft', value: 'viperaircraft' },
    { label: 'Vulcanair', value: 'vulcanair' },
    { label: 'Vulcanair Aircraft', value: 'vulcanairaircraft' },
    { label: 'Waco Aircraft Corporation', value: 'wacoaircraftcorporation' },
    { label: 'Westland Helicopters', value: 'westlandhelicopters' },
    { label: 'Zenith Aircraft Company', value: 'zenithaircraftcompany' },
    { label: 'Zlin Aircraft', value: 'zlinaircraft' },
    { label: 'Zlin Aviation', value: 'zlinaviation' },
  ]