export const cyclesData = [
    { label: 'A2B', value: 'a2b' },
    { label: 'Addmotor', value: 'addmotor' },
    { label: 'Alchemy', value: 'alchemy' },
    { label: 'All-City', value: 'allcity' },
    { label: 'Allied Cycle Works', value: 'alliedcycleworks' },
    { label: 'Ancheer', value: 'ancheer' },
    { label: 'Ariel Rider', value: 'arielrider' },
    { label: 'Aventon', value: 'aventon' },
    { label: 'Bacchetta', value: 'bacchetta' },
    { label: 'Bakcou', value: 'bakcou' },
    { label: 'Basso', value: 'basso' },
    { label: 'Batch', value: 'batch' },
    { label: 'Be One', value: 'beone' },
    { label: 'Benno', value: 'benno' },
    { label: 'BH', value: 'bh' },
    { label: 'BH Bikes', value: 'bhbikes' },
    { label: 'Bianchi', value: 'bianchi' },
    { label: 'Bintelli', value: 'bintelli' },
    { label: 'Birdy', value: 'birdy' },
    { label: 'Blix', value: 'blix' },
    { label: 'BMC', value: 'bmc' },
    { label: 'Boardman', value: 'boardman' },
    { label: 'Bombtrack', value: 'bombtrack' },
    { label: 'Breezer', value: 'breezer' },
    { label: 'Brompton', value: 'brompton' },
    { label: 'Bulls', value: 'bulls' },
    { label: 'Burley', value: 'burley' },
    { label: 'Cannondale', value: 'cannondale' },
    { label: 'Canyon', value: 'canyon' },
    { label: 'Cervélo', value: 'cervelo' },
    { label: 'Charge', value: 'charge' },
    { label: 'Cinelli', value: 'cinelli' },
    { label: 'Civia', value: 'civia' },
    { label: 'Colnago', value: 'colnago' },
    { label: 'Commencal', value: 'commencal' },
    { label: 'Co-op Cycles', value: 'coopcycles' },
    { label: 'Cotic', value: 'cotic' },
    { label: 'Cube', value: 'cube' },
    { label: 'Dahon', value: 'dahon' },
    { label: 'Dawes', value: 'dawes' },
    { label: 'De Rosa', value: 'derosa' },
    { label: 'Devinci', value: 'devinci' },
    { label: 'Diamondback', value: 'diamondback' },
    { label: 'DJ Bikes', value: 'djbikes' },
    { label: 'Ecotric', value: 'ecotric' },
    { label: 'Eddy Merckx', value: 'eddycycles' },
    { label: 'E-Joe', value: 'ejoe' },
    { label: 'Electra', value: 'electra' },
    { label: 'Elliptigo', value: 'elliptigo' },
    { label: 'Ellis', value: 'ellis' },
    { label: 'Ellsworth', value: 'ellsworth' },
    { label: 'Emojo', value: 'emojo' },
    { label: 'Engwe', value: 'engwe' },
    { label: 'Enzo', value: 'enzo' },
    { label: 'Eunorau', value: 'eunorau' },
    { label: 'Evelo', value: 'evelo' },
    { label: 'Evercross', value: 'evercross' },
    { label: 'Faraday', value: 'faraday' },
    { label: 'Felt', value: 'felt' },
    { label: 'Flyer', value: 'flyer' },
    { label: 'Focus', value: 'focus' },
    { label: 'Fondriest', value: 'fondriest' },
    { label: 'Fuji', value: 'fuji' },
    { label: 'Gazelle', value: 'gazelle' },
    { label: 'Generic', value: 'generic' },
    { label: 'Genesis', value: 'genesis' },
    { label: 'GenZe', value: 'genze' },
    { label: 'G-Force', value: 'gforce' },
    { label: 'Ghost', value: 'ghost' },
    { label: 'Giant', value: 'giant' },
    { label: 'Gocycle', value: 'gocycle' },
    { label: 'GreenBike', value: 'greenbike' },
    { label: 'Greenspeed', value: 'greenspeed' },
    { label: 'GT', value: 'gt' },
    { label: 'Haibike', value: 'haibike' },
    { label: 'Haro', value: 'haro' },
    { label: 'Hase', value: 'hase' },
    { label: 'Himiway', value: 'himiway' },
    { label: 'Holdsworth', value: 'holdsworth' },
    { label: 'HP Velotechnik', value: 'hpvelotechnik' },
    { label: 'Hyper', value: 'hyper' },
    { label: 'Ibis', value: 'ibis' },
    { label: 'ICE Trikes', value: 'icetrikes' },
    { label: 'iZip', value: 'izip' },
    { label: 'Jamis', value: 'jamis' },
    { label: 'Juiced Bikes', value: 'juicedbikes' },
    { label: 'Kalkhoff', value: 'kalkhoff' },
    { label: 'KBO', value: 'kbo' },
    { label: 'Kestrel', value: 'kestrel' },
    { label: 'Kettler', value: 'kettler' },
    { label: 'KHS', value: 'khs' },
    { label: 'Koga', value: 'koga' },
    { label: 'Kona', value: 'kona' },
    { label: 'Kross', value: 'kross' },
    { label: 'Lapierre', value: 'lapierre' },
    { label: 'Lectric', value: 'lectric' },
    { label: 'Litespeed', value: 'litespeed' },
    { label: 'Liteville', value: 'liteville' },
    { label: 'Look', value: 'look' },
    { label: 'Magnum', value: 'magnum' },
    { label: 'Marin', value: 'marin' },
    { label: 'Masi', value: 'masi' },
    { label: 'Merida', value: 'merida' },
    { label: 'Miyata', value: 'miyata' },
    { label: 'Mondraker', value: 'mondraker' },
    { label: 'Mongoose', value: 'mongoose' },
    { label: 'Montague', value: 'montague' },
    { label: 'Moots', value: 'moots' },
    { label: 'Motiv', value: 'motiv' },
    { label: 'Motobecane', value: 'motobecane' },
    { label: 'Moustache', value: 'moustache' },
    { label: 'Nakto', value: 'nakto' },
    { label: 'NCM', value: 'ncm' },
    { label: 'Niner', value: 'niner' },
    { label: 'Nishiki', value: 'nishiki' },
    { label: 'Noah’s Ark', value: 'noahsark' },
    { label: 'Norco', value: 'norco' },
    { label: 'NS Bikes', value: 'nsbikes' },
    { label: 'Orbea', value: 'orbea' },
    { label: 'Pedego', value: 'pedego' },
    { label: 'Pinarello', value: 'pinarello' },
    { label: 'Pinnacle', value: 'pinnacle' },
    { label: 'Pivot', value: 'pivot' },
    { label: 'Polygon', value: 'polygon' },
    { label: 'Priority', value: 'priority' },
    { label: 'ProdecoTech', value: 'prodecotech' },
    { label: 'Propella', value: 'propella' },
    { label: 'Pure Cycles', value: 'purecycles' },
    { label: 'QuietKat', value: 'quietkat' },
    { label: 'Rad', value: 'rad' },
    { label: 'Rad Power Bikes', value: 'radpowerbikes' },
    { label: 'Radon', value: 'radon' },
    { label: 'Raleigh', value: 'raleigh' },
    { label: 'Revel', value: 'revel' },
    { label: 'Ribble', value: 'ribble' },
    { label: 'Ride1Up', value: 'ride1up' },
    { label: 'Ridley', value: 'ridley' },
    { label: 'Riese & Müller', value: 'riesemuller' },
    { label: 'Ritchey', value: 'ritchey' },
    { label: 'Rockrider', value: 'rockrider' },
    { label: 'Rocky Mountain', value: 'rockymountain' },
    { label: 'Salsa', value: 'salsa' },
    { label: 'Santa Cruz', value: 'santacruz' },
    { label: 'Saracen', value: 'saracen' },
    { label: 'Schwinn', value: 'schwinn' },
    { label: 'Scott', value: 'scott' },
    { label: 'Sixthreezero', value: 'sixthreezero' },
    { label: 'Sonder', value: 'sonder' },
    { label: 'Sondors', value: 'sondors' },
    { label: 'Specialized', value: 'specialized' },
    { label: 'Stark Drive', value: 'starkdrive' },
    { label: 'State Bicycle Co.', value: 'statebicycleco' },
    { label: 'Stevens', value: 'stevens' },
    { label: 'Stromer', value: 'stromer' },
    { label: 'Surly', value: 'surly' },
    { label: 'Swagtron', value: 'swagtron' },
    { label: 'Tern', value: 'tern' },
    { label: 'Terratrike', value: 'terratrike' },
    { label: 'Time', value: 'time' },
    { label: 'Tommaso', value: 'tommaso' },
    { label: 'Trek', value: 'trek' },
    { label: 'Turner', value: 'turner' },
    { label: 'Univega', value: 'univega' },
    { label: 'Van Nicholas', value: 'vannicholas' },
    { label: 'VanMoof', value: 'vanmoof' },
    { label: 'Velotric', value: 'velotric' },
    { label: 'Vitória', value: 'vitoria' },
    { label: 'VoltBike', value: 'voltbike' },
    { label: 'Vvolt', value: 'vvolt' },
    { label: 'Watt', value: 'watt' },
    { label: 'Whyte', value: 'whyte' },
    { label: 'Wilier', value: 'wilier' },
    { label: 'Wilier Triestina', value: 'wiliertriestina' },
    { label: 'Wing', value: 'wing' },
    { label: 'Woom', value: 'woom' },
    { label: 'Xtracycle', value: 'xtracycle' },
    { label: 'Yamaha', value: 'yamaha' },
    { label: 'Yeti', value: 'yeti' },
    { label: 'Yeti Cycles', value: 'yeticycles' },
    { label: 'YT Industries', value: 'ytindustries' },
    { label: 'Yuba', value: 'yuba' },
    { label: 'Zerode', value: 'zerode' },
    { label: 'Zigo', value: 'zigo' },
    { label: 'Zizzo', value: 'zizzo' },
    { label: 'Zobop', value: 'zobop' },
  ]