export const vanData = [
  { label: 'Mercedes-Benz', value: 'mercedesbenz' },
  { label: 'MAN', value: 'man' },
  { label: 'Volkswagen', value: 'volkswagen' },
  { label: 'Iveco', value: 'iveco' },
  { label: 'Fiat', value: 'fiat' },
  { label: 'Renault', value: 'renault' },
  { label: 'Peugeot', value: 'peugeot' },
  { label: 'Citroën', value: 'citroen' },
  { label: 'Volvo', value: 'volvo' },
  { label: 'Scania', value: 'scania' },
  { label: 'Neoplan', value: 'neoplan' },
  { label: 'Setra', value: 'setra' },
  { label: 'Van Hool', value: 'vanhool' },
  { label: 'DAF', value: 'daf' },
  { label: 'VDL', value: 'vdl' },
  { label: 'Temsa', value: 'temsa' },
  { label: 'Otokar', value: 'otokar' },
  { label: 'Karsan', value: 'karsan' },
  { label: 'Ford', value: 'ford' },
  { label: 'GMC', value: 'gmc' },
  { label: 'Chevrolet', value: 'chevrolet' },
  { label: 'RAM', value: 'ram' },
  { label: 'Chrysler', value: 'chrysler' },
  { label: 'Dodge', value: 'dodge' },
  { label: 'Freightliner', value: 'freightliner' },
  { label: 'Thomas Built Buses', value: 'thomasbuiltbuses' },
  { label: 'Blue Bird', value: 'bluebird' },
  { label: 'Gillig', value: 'gillig' },
  { label: 'IC Bus', value: 'icbus' },
  { label: 'New Flyer', value: 'newflyer' },
  { label: 'Prevost', value: 'prevost' },
  { label: 'Motor Coach Industries (MCI)', value: 'motorcoachindustries' },
  { label: 'BYD', value: 'byd' },
  { label: 'Yutong', value: 'yutong' },
  { label: 'King Long', value: 'kinglong' },
  { label: 'Higer', value: 'higer' },
  { label: 'Golden Dragon', value: 'goldendragon' },
  { label: 'Ankai', value: 'ankai' },
  { label: 'Zhongtong', value: 'zhongtong' },
  { label: 'Youngman', value: 'youngman' },
  { label: 'Foton', value: 'foton' },
  { label: 'Dongfeng', value: 'dongfeng' },
  { label: 'Changan', value: 'changan' },
  { label: 'JAC Motors', value: 'jacmotors' },
  { label: 'Hino', value: 'hino' },
  { label: 'Toyota', value: 'toyota' },
  { label: 'Nissan', value: 'nissan' },
  { label: 'Isuzu', value: 'isuzu' },
  { label: 'Mitsubishi Fuso', value: 'mitsubishifuso' },
  { label: 'Mazda', value: 'mazda' },
  { label: 'Honda', value: 'honda' },
  { label: 'Suzuki', value: 'suzuki' },
  { label: 'Hyundai', value: 'hyundai' },
  { label: 'Kia', value: 'kia' },
  { label: 'Daewoo', value: 'daewoo' },
  { label: 'Tata Motors', value: 'tatamotors' },
  { label: 'Ashok Leyland', value: 'ashokleyland' },
  { label: 'Eicher', value: 'eicher' },
  { label: 'Mahindra', value: 'mahindra' },
  { label: 'Force Motors', value: 'forcemotors' },
  { label: 'Marcopolo', value: 'marcopolo' },
  { label: 'Caio', value: 'caio' },
  { label: 'Volgren', value: 'volgren' },
  { label: 'Irizar', value: 'irizar' },
  { label: 'TAM', value: 'tam' },
  { label: 'Solaris', value: 'solaris' },
  { label: 'Autosan', value: 'autosan' },
  { label: 'Vanool', value: 'vanool' },
  { label: 'Optare', value: 'optare' },
  { label: 'Alexander Dennis', value: 'alexanderdennis' },
  { label: 'Wrightbus', value: 'wrightbus' },
  { label: 'Dennis Eagle', value: 'denniseagle' },
  { label: 'Plaxton', value: 'plaxton' },
  { label: 'Rosan', value: 'rosan' },
  { label: 'Ikarus', value: 'ikarus' },
  { label: 'Kässbohrer', value: 'kassbohrer' },
  { label: 'Kuban', value: 'kuban' },
  { label: 'PAZ', value: 'paz' },
  { label: 'UAZ', value: 'uaz' },
  { label: 'GAZ', value: 'gaz' },
  { label: 'Belarusian Automobile Plant', value: 'belarusianautomobileplant' },
  { label: 'BMC', value: 'bmc' },
  { label: 'Karosa', value: 'karosa' },
  { label: 'Sanos', value: 'sanos' },
  { label: 'Skoda', value: 'skoda' },
  { label: 'Jelcz', value: 'jelcz' },
  { label: 'VDL Berkhof', value: 'vdlberkhof' },
  { label: 'Carrus', value: 'carrus' },
  { label: 'Vest', value: 'vest' },
  { label: 'Sileo', value: 'sileo' },
  { label: 'Multicar', value: 'multicar' },
  { label: 'KamAZ', value: 'kamaz' },
  { label: 'LiAZ', value: 'liaz' },
  { label: 'Moscow Trolleybus Factory', value: 'moscowtrolleybusfactory' },
  { label: 'Autokar', value: 'autokar' },
  { label: 'ZAZ', value: 'zaz' },
  { label: 'Bogdan', value: 'bogdan' },
  { label: 'LAZ', value: 'laz' },
  { label: 'KrAZ', value: 'kraz' },
  { label: 'Robur', value: 'robur' },
  { label: 'Rocar', value: 'rocar' },
  { label: 'Iveco Magirus', value: 'ivecomagirus' },
  { label: 'Wartburg', value: 'wartburg' },
  { label: 'Sisu', value: 'sisu' },
  { label: 'MAZ', value: 'maz' },
  { label: 'Praga', value: 'praga' },
  { label: 'Star', value: 'star' },
  { label: 'Scania-Vabis', value: 'scaniavabis' },
  { label: 'FAMSA', value: 'famsa' },
  { label: 'Anhui Ankai', value: 'anhuiankai' },
  { label: 'King Long United Automotive', value: 'kinglongunitedautomotive' },
  { label: 'GAC Group', value: 'gacgroup' },
  { label: 'Guangzhou Yangcheng', value: 'guangzhouyangcheng' },
  { label: 'Jiangxi Kama', value: 'jiangxikama' },
  { label: 'Shanghai Shenlong', value: 'shanghaishenlong' },
  { label: 'Zhongtong Bus', value: 'zhongtongbus' },
  { label: 'Beijing Bus', value: 'beijingbus' },
  { label: 'Xiamen King Long', value: 'xiamenkinglong' },
  { label: 'Dandong Huanghai', value: 'dandonghuanghai' },
  { label: 'Shenyang Jinbei', value: 'shenyangjinbei' },
  { label: 'Hebei Yutong', value: 'hebeiyutong' },
  { label: 'Hunan Bus', value: 'hunanbus' },
  { label: 'Zhengzhou Yutong', value: 'zhengzhouyutong' },
  { label: 'Shenzhen Wuzhoulong', value: 'shenzhenwuzhoulong' },
  { label: 'Haima', value: 'haima' },
  { label: 'Hafei', value: 'hafei' },
  { label: 'Foton AUV', value: 'fotonauv' },
  { label: 'XCMG', value: 'xcmg' },
  { label: 'FAW Bus and Coach', value: 'fawbusandcoach' },
  { label: 'Guilin Daewoo', value: 'guilindaewoo' },
  { label: 'Suzhou Higer', value: 'suzhouhiger' },
  { label: 'Dongfeng Motor Corporation', value: 'dongfengmotorcorporation' },
  { label: 'SAIC Motor', value: 'saicmotor' },
  { label: 'FAW Jiefang', value: 'fawjiefang' },
  { label: 'Nanjing Automobile', value: 'nanjingautomobile' },
  { label: 'Shaanxi Automobile', value: 'shaanxiautomobile' },
  { label: 'Chery', value: 'chery' },
  { label: 'Geely', value: 'geely' },
  { label: 'Great Wall Motors', value: 'greatwallmotors' },
  { label: 'Hongqi', value: 'hongqi' },
  { label: 'Dongfeng Sokon', value: 'dongfengsokon' },
  { label: 'Higer Bus', value: 'higerbus' },
  { label: 'Xiamen Golden Dragon', value: 'xiamengoldendragon' },
  { label: 'Beiqi Foton', value: 'beiqifoton' },
  { label: 'Changjiang', value: 'changjiang' },
  { label: 'JAC', value: 'jac' },
  { label: 'Baoding Changda', value: 'baodingchangda' },
  { label: 'Qingdao Haier', value: 'qingdaohaier' },
  { label: 'Yinlong', value: 'yinlong' },
  { label: 'Zhengzhou Nissan', value: 'zhengzhounissan' },
  { label: 'GAC Trumpchi', value: 'gactrumpchi' },
  { label: 'YTO', value: 'yto' },
  { label: 'Xiamen Auto', value: 'xiamenauto' },
  { label: 'Guangxi Yuchai', value: 'guangxiyuchai' },
  { label: 'Jianghuai', value: 'jianghuai' },
  { label: 'Zhongxing', value: 'zhongxing' },
  { label: 'Weichai Power', value: 'weichai' },
  { label: 'Shaolin Bus', value: 'shaolinbus' },
  { label: 'Wuzhoulong', value: 'wuzhoulong' },
  { label: 'Shenlong', value: 'shenlong' },
  { label: 'Great Wall', value: 'greatwall' },
  { label: 'FAW', value: 'faw' },
  { label: 'SAIC', value: 'saic' },
  { label: 'BAIC', value: 'baic' },
  { label: 'Lifan', value: 'lifan' },
  { label: 'Fawer', value: 'fawer' },
  { label: 'Naveco', value: 'naveco' },
  { label: 'Shaanxi Auto', value: 'shaanxiauto' },
  { label: 'JMC', value: 'jmc' },
  { label: 'Dongfeng Motor', value: 'dongfengmotor' },
  { label: 'Weichai', value: 'weichai' },
  { label: 'Shaolin', value: 'shaolin' },
  { label: 'GAC', value: 'gac' },
  { label: 'Baoding', value: 'baoding' },
  { label: 'Shandong KAMA', value: 'shandongkama' },
  { label: 'A.B. Volvo', value: 'abvolvo' },
  { label: 'Aero', value: 'aero' },
  { label: 'Agrale', value: 'agrale' },
  { label: 'AinBus', value: 'ainbus' },
  { label: 'Alfa Bus', value: 'alfabus' },
  { label: 'Allison', value: 'allison' },
  { label: 'AltaVista Motors', value: 'altavistamotors' },
  { label: 'AM General', value: 'amgeneral' },
  { label: 'Ameritrans', value: 'ameritrans' },
  { label: 'Apolo', value: 'apolo' },
  { label: 'Arboc', value: 'arboc' },
  { label: 'Arcola', value: 'arcola' },
  { label: 'Arkomat', value: 'arkomat' },
  { label: 'Astra', value: 'astra' },
  { label: 'Atco', value: 'atco' },
  { label: 'Atul', value: 'atul' },
  { label: 'Autobus Classique', value: 'autobusclassique' },
  { label: 'Auto Cuby', value: 'autocuby' },
  { label: 'Aveva', value: 'aveva' },
  { label: 'Baic Motor', value: 'baicmotor' },
  { label: 'Barker Bus', value: 'barkerbus' },
  { label: 'Baron Bus', value: 'baronbus' },
  { label: 'Benzhou', value: 'benzhou' },
  { label: 'BharatBenz', value: 'bharatbenz' },
  { label: 'Bianchi', value: 'bianchi' },
  { label: 'Bridgestone', value: 'bridgestone' },
  { label: 'Brilliance', value: 'brilliance' },
  { label: 'Britz', value: 'britz' },
  { label: 'Camiones', value: 'camiones' },
  { label: 'Canter', value: 'canter' },
  { label: 'Caravaggio', value: 'caravaggio' },
  { label: 'Carrossel', value: 'carrossel' },
  { label: 'Carso', value: 'carso' },
  { label: 'CenCar', value: 'cencar' },
  { label: 'Chang’an', value: 'changan' },
  { label: 'Chery Commercial', value: 'cherycommercial' },
  { label: 'Cimc Huajun', value: 'cimchuajun' },
  { label: 'CoachUSA', value: 'coachusa' },
  { label: 'Coast Mountain', value: 'coastmountain' },
  { label: 'Collins Bus', value: 'collinsbus' },
  { label: 'ComfortDelGro', value: 'comfortdelgro' },
  { label: 'Cosbus', value: 'cosbus' },
  { label: 'Coventry', value: 'coventry' },
  { label: 'Crown Coach', value: 'crowncoach' },
  { label: 'Dacia', value: 'dacia' },
  { label: 'Daimler', value: 'daimler' },
  { label: 'Danfoss', value: 'danfoss' },
  { label: 'Dennis', value: 'dennis' },
  { label: 'Designline', value: 'designline' },
  { label: 'DFM', value: 'dfm' },
  { label: 'DINA', value: 'dina' },
  { label: 'Dotto', value: 'dotto' },
  { label: 'Durabus', value: 'durabus' },
  { label: 'ElDorado', value: 'eldorado' },
  { label: 'Elkhart Coach', value: 'elkhartcoach' },
  { label: 'Ellison', value: 'ellison' },
  { label: 'Erskine', value: 'erskine' },
  { label: 'ETR', value: 'etr' },
  { label: 'Fecon', value: 'fecon' },
  { label: 'Ferronorte', value: 'ferronorte' },
  { label: 'Figi', value: 'figi' },
  { label: 'Fleetwood', value: 'fleetwood' },
  { label: 'Freedman', value: 'freedman' },
  { label: 'Freightway', value: 'freightway' },
  { label: 'Fujian', value: 'fujian' },
  { label: 'Fuji Heavy Industries', value: 'fujiheavyindustries' },
  { label: 'Fuso', value: 'fuso' },
  { label: 'Gersthofen', value: 'gersthofen' },
  { label: 'Greeves', value: 'greeves' },
  { label: 'Griswold', value: 'griswold' },
  { label: 'Groupe PSA', value: 'groupepsa' },
  { label: 'Guerrero', value: 'guerrero' },
  { label: 'Halmstad', value: 'halmstad' },
  { label: 'Haniffa', value: 'haniffa' },
  { label: 'Harbin', value: 'harbin' },
  { label: 'Hawtai', value: 'hawtai' },
  { label: 'Heuliez', value: 'heuliez' },
  { label: 'Hobson', value: 'hobson' },
  { label: 'Hualing', value: 'hualing' },
  { label: 'Hualong', value: 'hualong' },
  { label: 'Huanghai', value: 'huanghai' },
  { label: 'Hyzon', value: 'hyzon' },
  { label: 'Ikarbus', value: 'ikarbus' },
  { label: 'Iling', value: 'iling' },
  { label: 'Indcar', value: 'indcar' },
  { label: 'International', value: 'international' },
  { label: 'JAC Sunray', value: 'jacsunray' },
  { label: 'Jawa', value: 'jawa' },
  { label: 'JCBL', value: 'jcbl' },
  { label: 'Jeep', value: 'jeep' },
  { label: 'Jinbei', value: 'jinbei' },
  { label: 'Keio', value: 'keio' },
  { label: 'Kenworth', value: 'kenworth' },
  { label: 'Kingtec', value: 'kingtec' },
  { label: 'KMC', value: 'kmc' },
  { label: 'Komatsu', value: 'komatsu' },
  { label: 'Kovatch', value: 'kovatch' },
  { label: 'LAG', value: 'lag' },
  { label: 'LADA', value: 'lada' },
  { label: 'LECIP', value: 'lecip' },
  { label: 'Lindner', value: 'lindner' },
  { label: 'Lion Bus', value: 'lionbus' },
  { label: 'Lodal', value: 'lodal' },
  { label: 'Luxgen', value: 'luxgen' },
  { label: 'Macrotech', value: 'macrotech' },
  { label: 'Manheim', value: 'manheim' },
  { label: 'Maserati', value: 'maserati' },
  { label: 'Massey Ferguson', value: 'masseyferguson' },
  { label: 'Master', value: 'master' },
  { label: 'Meritor', value: 'meritor' },
  { label: 'Metropol', value: 'metropol' },
  { label: 'Minibus', value: 'minibus' },
  { label: 'Minerva', value: 'minerva' },
  { label: 'Mitsubishi', value: 'mitsubishi' },
  { label: 'Mitsubishi Minicab', value: 'mitsubishiminicab' },
  { label: 'Mitsubishi Motors', value: 'mitsubishimotors' },
  { label: 'Mitsubishi Rosa', value: 'mitsubishirosa' },
  { label: 'Mitsubishi Shogun', value: 'mitsubishishogun' },
  { label: 'Mobility Ventures', value: 'mobilityventures' },
  { label: 'Nabi', value: 'nabi' },
  { label: 'Nanchang', value: 'nanchang' },
  { label: 'Naveco Power', value: 'navecopower' },
  { label: 'Ningbo', value: 'ningbo' },
  { label: 'Nissan Diesel', value: 'nissandiesel' },
  { label: 'Nissan NV', value: 'nissannv' },
  { label: 'Northern Coachbuilders', value: 'northerncoachbuilders' },
  { label: 'Opel', value: 'opel' },
  { label: 'Orion', value: 'orion' },
  { label: 'Peerless', value: 'peerless' },
  { label: 'Pegaso', value: 'pegaso' },
  { label: 'Piaggio', value: 'piaggio' },
  { label: 'Polarsun', value: 'polarsun' },
  { label: 'Porsche', value: 'porsche' },
  { label: 'Premier', value: 'premier' },
  { label: 'Proterra', value: 'proterra' },
  { label: 'PSA Peugeot Citroën', value: 'psapeugeotcitroen' },
  { label: 'Puma', value: 'puma' },
  { label: 'Qingdao', value: 'qingdao' },
  { label: 'Qingling', value: 'qingling' },
  { label: 'Qoros', value: 'qoros' },
  { label: 'Qvale', value: 'qvale' },
  { label: 'Renault Trucks', value: 'renaulttrucks' },
  { label: 'Rhodes', value: 'rhodes' },
  { label: 'Rolls-Royce', value: 'rollsroyce' },
  { label: 'Rosa', value: 'rosa' },
  { label: 'Rosenbauer', value: 'rosenbauer' },
  { label: 'Rover', value: 'rover' },
  { label: 'Royal Enfield', value: 'royalenfield' },
  { label: 'Ruf', value: 'ruf' },
  { label: 'Rusted', value: 'rusted' },
  { label: 'SAAB', value: 'saab' },
  { label: 'Saj', value: 'saj' },
  { label: 'Sakai', value: 'sakai' },
  { label: 'Sampaio', value: 'sampaio' },
  { label: 'Schmitz', value: 'schmitz' },
  { label: 'Schwaben', value: 'schwaben' },
  { label: 'Shenyang', value: 'shenyang' },
  { label: 'Shinjin', value: 'shinjin' },
  { label: 'Sinotruck', value: 'sinotruck' },
  { label: 'Solerbus', value: 'solerbus' },
  { label: 'Spartan', value: 'spartan' },
  { label: 'SsangYong', value: 'ssangyong' },
  { label: 'Starcraft', value: 'starcraft' },
  { label: 'Subaru', value: 'subaru' },
  { label: 'Swift', value: 'swift' },
  { label: 'Tanker', value: 'tanker' },
  { label: 'Tez', value: 'tez' },
  { label: 'TMC', value: 'tmc' },
  { label: 'TMT', value: 'tmt' },
  { label: 'Trojan', value: 'trojan' },
  { label: 'United Bus', value: 'unitedbus' },
  { label: 'Vauxhall', value: 'vauxhall' },
  { label: 'VECV', value: 'vecv' },
  { label: 'WABCO', value: 'wabco' },
  { label: 'Waldner', value: 'waldner' },
  { label: 'Wanderer', value: 'wanderer' },
  { label: 'Westport', value: 'westport' },
  { label: 'Wuling', value: 'wuling' },
  { label: 'Xiali', value: 'xiali' },
  { label: 'Xingyue', value: 'xingyue' },
  { label: 'Yamaha', value: 'yamaha' },
  { label: 'Yaxing', value: 'yaxing' },
  { label: 'Yuejin', value: 'yuejin' },
  { label: 'YueLoong', value: 'yueloong' },
  { label: 'Zastava', value: 'zastava' },
  { label: 'Zotye', value: 'zotye' },
  { label: 'Zyle Daewoo', value: 'zyledaewoo' },
]
